using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for a collection item that behaves like a leaf control: it is clicked, it
/// says something, and it can be disabled.
/// </summary>
/// <remarks>
/// <para>
/// An item is a <see cref="ItemContainerBase{TCollection, TSelf}"/> rather than a control
/// because <see cref="CollectionObjectBase{TParent, TSelf, TItem}"/> hands out containers -
/// that is what gives the item its own root and lets a chain stay on the item. The price is
/// that a leaf item cannot inherit <see cref="ClickableControlBase{TScope}"/>, so the two
/// or three members a leaf needs live here instead, once, for every item type that wants
/// them.
/// </para>
/// <para>
/// Existence and visibility are not declared here: <see cref="ContainerObjectBase{TParent,
/// TSelf}"/> already answers both against the item's root.
/// </para>
/// </remarks>
/// <typeparam name="TCollection">The owning collection.</typeparam>
/// <typeparam name="TSelf">The item type itself (self-referencing for fluent returns).</typeparam>

public abstract partial class ClickableItemBase<TCollection, TSelf> : ItemContainerBase<TCollection, TSelf>
    where TCollection : IMauiScope<TCollection>, IItemRootProvider
    where TSelf : ClickableItemBase<TCollection, TSelf>
{
    #region Click

    public TSelf Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Text (GetText / WaitText / AssertText)

    public string? GetText(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTextCore(element), timeoutMs);
    }

    public bool? WaitText(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element) == expected,
           timeoutMs);
    }

    public TSelf AssertText(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Text to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextContains(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.Contains(expected!) == true,
           timeoutMs);
    }

    public TSelf AssertTextContains(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.Contains(expected1!) == true),
           message ?? $"Expected TextContains to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextEmpty(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => string.IsNullOrEmpty(GetTextCore(element)) == expected,
           timeoutMs);
    }

    public TSelf AssertTextEmpty(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => (bool?)string.IsNullOrEmpty(GetTextCore(element)), (actual, expected1) => (actual == expected1),
           message ?? $"Expected TextEmpty to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Enabled (IsEnabled / WaitEnabled / AssertEnabled)

    public bool? IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsEnabledCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Enabled to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
