// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for MAUI controls with click capability.
/// Implements IClickableControlObject with Click, DoubleClick, RightClick, Hover, LongPress.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public abstract partial class ClickableControlBase<TScope> : FocusableControlBase<TScope>,
    IClickableControlObject<TScope>,
    IPressableControl<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Click

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region DoubleClick

    public TScope DoubleClick(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { DoubleClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region RightClick

    public TScope RightClick(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { RightClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Hover

    public TScope Hover(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { HoverCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region LongPress

    public TScope LongPress(int? durationMs = null, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { LongPressCore(element, durationMs, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Press

    public TScope Press(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PressCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Clickable (IsClickable / WaitClickable / AssertClickable)

    public bool? IsClickable()
    {
        return IsClickableCore(TryFindElement()) == true;
    }

    public bool WaitClickable(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsClickableCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertClickable(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsClickableCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Clickable to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
