// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for MAUI controls with focus capability.
/// Implements IFocusableControlObject with Focus, Blur, IsFocused.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public abstract partial class FocusableControlBase<TScope> : ViewBase<TScope>, IFocusableControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Focus

    public TScope Focus(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { FocusCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Blur

    public TScope Blur(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { BlurCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Focused (IsFocused / WaitFocused / AssertFocused)

    public bool? IsFocused()
    {
        return IsFocusedCore(TryFindElement()) == true;
    }

    public bool WaitFocused(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsFocusedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertFocused(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsFocusedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Focused to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
