// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for MAUI controls with range/numeric capability.
/// Implements IRangeControlObject with GetValue, SetValue, Increment, Decrement.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public abstract partial class RangeControlBase<TScope> : FocusableControlBase<TScope>,
    IRangeControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Value (GetValue / WaitValue / AssertValue)

    public double? GetValue(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetValueCore(element), timeoutMs);
    }

    public bool? WaitValue(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetValueCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertValue(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetValueCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Value to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SetValue

    public TScope SetValue(double? value, int? timeoutMs = null)
    {
        return RunSetWithElement(value, element => { SetValueCore(element, value, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Minimum (GetMinimum / WaitMinimum / AssertMinimum)

    public double? GetMinimum(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetMinimumCore(element), timeoutMs);
    }

    public bool? WaitMinimum(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetMinimumCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertMinimum(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetMinimumCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Minimum to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Maximum (GetMaximum / WaitMaximum / AssertMaximum)

    public double? GetMaximum(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetMaximumCore(element), timeoutMs);
    }

    public bool? WaitMaximum(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetMaximumCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertMaximum(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetMaximumCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Maximum to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Step (GetStep / WaitStep / AssertStep)

    public double? GetStep(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetStepCore(element), timeoutMs);
    }

    public bool? WaitStep(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetStepCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertStep(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetStepCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Step to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Increment

    public TScope Increment(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { IncrementCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Decrement

    public TScope Decrement(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { DecrementCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion

}
