using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// A collection item that can be the current one: a tab, a flyout entry, a list row.
/// </summary>
/// <remarks>
/// Selection is the one thing a navigation item knows that a plain clickable item does not,
/// and reading it is the same everywhere, so it lives here rather than in each item type.
/// </remarks>
/// <typeparam name="TCollection">The owning collection.</typeparam>
/// <typeparam name="TSelf">The item type itself (self-referencing for fluent returns).</typeparam>

public abstract partial class SelectableItemBase<TCollection, TSelf> : ClickableItemBase<TCollection, TSelf>
    where TCollection : IMauiScope<TCollection>, IItemRootProvider
    where TSelf : SelectableItemBase<TCollection, TSelf>
{
    #region Selected (IsSelected / WaitSelected / AssertSelected)

    public bool? IsSelected()
    {
        return IsSelectedCore(TryFindElement()) == true;
    }

    public bool WaitSelected(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsSelectedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertSelected(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsSelectedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Selected to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
