// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for MAUI controls with selection capability.
/// Implements ISelectorControlObject with SelectByText, SelectByIndex, GetSelectedText.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public abstract partial class SelectorControlBase<TScope> : FocusableControlBase<TScope>,
    ISelectorControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SelectByText

    public TScope SelectByText(string? text, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SelectByTextCore(element, text, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SelectByIndex

    public TScope SelectByIndex(int? index, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SelectByIndexCore(element, index, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SelectByValue

    public TScope SelectByValue(string? value, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SelectByValueCore(element, value, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SelectedText (GetSelectedText / WaitSelectedText / AssertSelectedText)

    public string? GetSelectedText(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetSelectedTextCore(element), timeoutMs);
    }

    public bool? WaitSelectedText(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSelectedTextCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertSelectedText(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSelectedTextCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected SelectedText to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SelectedIndex (GetSelectedIndex / WaitSelectedIndex / AssertSelectedIndex)

    public int? GetSelectedIndex(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetSelectedIndexCore(element), timeoutMs);
    }

    public bool? WaitSelectedIndex(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSelectedIndexCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertSelectedIndex(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSelectedIndexCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected SelectedIndex to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region ItemCount (GetItemCount / WaitItemCount / AssertItemCount)

    public int? GetItemCount(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetItemCountCore(element), timeoutMs);
    }

    public bool? WaitItemCount(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetItemCountCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertItemCount(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetItemCountCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected ItemCount to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
