using Brinell.Maui.Configuration;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for MAUI controls with toggle capability.
/// Implements IToggleControlObject with Toggle, Check, Uncheck, SetChecked, and Click.
/// </summary>
/// <remarks>
/// <para>
/// <b>Focusable, not clickable</b> (step 102, option B). This used to derive from
/// <c>ClickableControlBase</c>, which gave every switch, check box and radio button a generated
/// <c>DoubleClick</c>, <c>RightClick</c>, <c>Hover</c>, <c>LongPress</c>, <c>Press</c> and
/// <c>IsClickable</c>/<c>WaitClickable</c>/<c>AssertClickable</c>. None of them means anything
/// for a toggle, the first four exist only as real pointer input on Windows - which the quiet
/// default refuses - and <c>Click</c> had to be overridden to mean something else anyway.
/// </para>
/// <para>
/// <c>Click</c> stays, declared here for what it is on a toggle: flipping it.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public abstract partial class ToggleControlBase<TScope> : FocusableControlBase<TScope>,
    IToggleControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Click

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Toggle

    public TScope Toggle(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ToggleCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetChecked

    public TScope SetChecked(bool? @checked, int? timeoutMs = null)
    {
        return RunSetWithElement(@checked, element => { SetCheckedCore(element, @checked, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Checked (IsChecked / WaitChecked / AssertChecked)

    public bool? IsChecked()
    {
        return IsCheckedCore(TryFindElement()) == true;
    }

    public bool WaitChecked(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsCheckedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertChecked(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsCheckedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Checked to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
