using Brinell.Maui.Configuration;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for MAUI controls with toggle capability.
/// Implements IToggleControlObject with Toggle, Check, Uncheck, SetChecked.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public abstract partial class ToggleControlBase<TScope> : ClickableControlBase<TScope>,
    IToggleControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Toggle

    public TScope Toggle(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ToggleCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetChecked

    public TScope SetChecked(bool? @checked, int? timeoutMs = null)
    {
        return RunSetWithElement(@checked, element => { SetCheckedCore(element, @checked, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Checked (IsChecked / WaitChecked / AssertChecked)

    public bool? IsChecked()
    {
        return IsCheckedCore(TryFindElement()) == true;
    }

    public bool WaitChecked(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsCheckedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertChecked(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsCheckedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Checked to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
