using Brinell.Core.Abstractions.Controls;
using Brinell.Core.Utilities;
using System.Runtime.CompilerServices;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Base;


/// <summary>
/// Base class for all MAUI controls implementing the Is/Wait/Assert pattern with fluent chaining.
/// Controls find elements within their scope (page, container, or list item).
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent method chaining.</typeparam>

public abstract partial class ViewBase<TScope> : ControlObjectBase<TScope>, IElementObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Visible (IsVisible / WaitVisible / AssertVisible)

    public bool? IsVisible()
    {
        return IsVisibleCore(TryFindElement()) == true;
    }

    public bool WaitVisible(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsVisibleCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertVisible(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsVisibleCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Visible to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Enabled (IsEnabled / WaitEnabled / AssertEnabled)

    public bool? IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsEnabledCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Enabled to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Attribute (GetAttribute / WaitAttribute / AssertAttribute)

    public string? GetAttribute(string? name, int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetAttributeCore(element, name), timeoutMs);
    }

    public bool? WaitAttribute(string? name, string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetAttributeCore(element, name) == expected,
           timeoutMs);
    }

    public TScope AssertAttribute(string? name, string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetAttributeCore(element, name), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Attribute to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region ScrollIntoView

    public TScope ScrollIntoView()
    {
        return RunDoWithElement(element => { ScrollIntoViewCore(element); });
    }

    #endregion

}
