using Brinell.Core;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Text;


/// <summary>
/// MAUI Editor control for multi-line text input.
/// Inherits all text manipulation from Entry.
/// Includes FlaUI-specific clear handling for Windows.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Editor<TScope> : Entry<TScope>
    where TScope : IMauiScope<TScope>
{

}
