using Brinell.Core;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Text;


/// <summary>
/// MAUI Entry control with text input capability and fluent method chaining.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Entry<TScope> : Base.FocusableControlBase<TScope>, IEditableTextControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Text (GetText / WaitText / AssertText)

    public string? GetText(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTextCore(element), timeoutMs);
    }

    public bool? WaitText(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertText(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Text to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextContains(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.Contains(expected!) == true,
           timeoutMs);
    }

    public TScope AssertTextContains(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.Contains(expected1!) == true),
           message ?? $"Expected TextContains to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextStartsWith(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.StartsWith(expected!) == true,
           timeoutMs);
    }

    public TScope AssertTextStartsWith(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.StartsWith(expected1!) == true),
           message ?? $"Expected TextStartsWith to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextEndsWith(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.EndsWith(expected!) == true,
           timeoutMs);
    }

    public TScope AssertTextEndsWith(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.EndsWith(expected1!) == true),
           message ?? $"Expected TextEndsWith to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextEmpty(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => string.IsNullOrEmpty(GetTextCore(element)) == expected,
           timeoutMs);
    }

    public TScope AssertTextEmpty(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => (bool?)string.IsNullOrEmpty(GetTextCore(element)), (actual, expected1) => (actual == expected1),
           message ?? $"Expected TextEmpty to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Clear

    public TScope Clear(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClearCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetText

    public TScope SetText(string? text, int? timeoutMs = null)
    {
        return RunSetWithElement(text, element => { SetTextCore(element, text, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Append

    public TScope Append(string? text, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { AppendCore(element, text, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Submit

    public TScope Submit(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SubmitCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Placeholder (GetPlaceholder / WaitPlaceholder / AssertPlaceholder)

    public string? GetPlaceholder(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPlaceholderCore(element), timeoutMs);
    }

    public bool? WaitPlaceholder(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPlaceholderCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertPlaceholder(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPlaceholderCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Placeholder to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region ReadOnly (IsReadOnly / WaitReadOnly / AssertReadOnly)

    public bool? IsReadOnly()
    {
        return IsReadOnlyCore(TryFindElement()) == true;
    }

    public bool WaitReadOnly(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsReadOnlyCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertReadOnly(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsReadOnlyCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected ReadOnly to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
