// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Text;


/// <summary>
/// MAUI SearchBar control for search text input with search action support.
/// Inherits all text manipulation from Entry, adds search-specific methods.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class SearchBar<TScope> : Entry<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SetSearch

    public TScope SetSearch(string? searchText, int? timeoutMs = null)
    {
        return RunSetWithElement(searchText, element => { SetSearchCore(element, searchText, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SubmitSearch

    public TScope SubmitSearch(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SubmitSearchCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion

}
