// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.DateTimes;


/// <summary>
/// MAUI DatePicker control for date selection.
/// Provides GetDate, SetDate, and date assertion methods.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class DatePicker<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region DateValue (GetDateValue / WaitDateValue / AssertDateValue)

    public System.DateTime? GetDateValue(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetDateValueCore(element), timeoutMs);
    }

    public bool? WaitDateValue(System.DateTime? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetDateValueCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertDateValue(System.DateTime? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetDateValueCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected DateValue to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region MinimumDate (GetMinimumDate / WaitMinimumDate / AssertMinimumDate)

    public System.DateTime? GetMinimumDate(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetMinimumDateCore(element), timeoutMs);
    }

    public bool? WaitMinimumDate(System.DateTime? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetMinimumDateCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertMinimumDate(System.DateTime? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetMinimumDateCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected MinimumDate to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region MaximumDate (GetMaximumDate / WaitMaximumDate / AssertMaximumDate)

    public System.DateTime? GetMaximumDate(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetMaximumDateCore(element), timeoutMs);
    }

    public bool? WaitMaximumDate(System.DateTime? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetMaximumDateCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertMaximumDate(System.DateTime? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetMaximumDateCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected MaximumDate to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SetDate

    public TScope SetDate(System.DateTime? date, int? timeoutMs = null)
    {
        return RunSetWithElement(date, element => { SetDateCore(element, date, timeoutMs); }, timeoutMs);
    }

    #endregion

}
