using Brinell.Core;
using Brinell.Core.Utilities;
using System.Linq;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.DateTimes;


/// <summary>
/// MAUI DatePicker control for date selection.
/// Provides GetDate, SetDate, and date assertion methods.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class DatePicker<TScope> : Base.FocusableControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SetDate

    public TScope SetDate(System.DateTime? date, int? timeoutMs = null)
    {
        return RunSetWithElement(date, element => { SetDateCore(element, date, timeoutMs); }, timeoutMs);
    }

    #endregion

}
