using Brinell.Core;
using Brinell.Core.Utilities;
using System.Linq;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.DateTimes;


/// <summary>
/// MAUI TimePicker control for time selection.
/// Provides GetTime, SetTime, and time assertion methods.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TimePicker<TScope> : Base.FocusableControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SetTime

    public TScope SetTime(TimeSpan? time, int? timeoutMs = null)
    {
        return RunSetWithElement(time, element => { SetTimeCore(element, time, timeoutMs); }, timeoutMs);
    }

    #endregion

}
