// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.DateTimes;


/// <summary>
/// MAUI TimePicker control for time selection.
/// Provides GetTime, SetTime, and time assertion methods.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TimePicker<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region TimeValue (GetTimeValue / WaitTimeValue / AssertTimeValue)

    public TimeSpan? GetTimeValue(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTimeValueCore(element), timeoutMs);
    }

    public bool? WaitTimeValue(TimeSpan? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTimeValueCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertTimeValue(TimeSpan? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTimeValueCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected TimeValue to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SetTime

    public TScope SetTime(TimeSpan? time, int? timeoutMs = null)
    {
        return RunSetWithElement(time, element => { SetTimeCore(element, time, timeoutMs); }, timeoutMs);
    }

    #endregion

}
