using Brinell.Maui.Containers;
using Brinell.Maui.Controls.Buttons;
using Brinell.Maui.Controls.Text;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Dialogs;


/// <summary>
/// MAUI ContentDialog control for WinUI3 popups produced by DisplayAlert and
/// DisplayPromptAsync.
/// </summary>
/// <typeparam name="TParent">The parent scope type.</typeparam>

public partial class ContentDialog<TParent> : ContainerObjectBase<TParent, ContentDialog<TParent>>
    where TParent : IMauiScope<TParent>
{
    #region Title (GetTitle / WaitTitle / AssertTitle)

    public string? GetTitle(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTitleCore(element), timeoutMs);
    }

    public bool WaitTitle(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTitleCore(element) == expected,
           timeoutMs);
    }

    public ContentDialog<TParent> AssertTitle(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTitleCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Title to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region ButtonTexts (GetButtonTexts / WaitButtonTexts / AssertButtonTexts)

    public IReadOnlyList<string>? GetButtonTexts(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetButtonTextsCore(element), timeoutMs);
    }

    public bool WaitButtonTexts(IReadOnlyList<string>? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetButtonTextsCore(element)?.SequenceEqual(expected!) == true,
           timeoutMs);
    }

    public ContentDialog<TParent> AssertButtonTexts(IReadOnlyList<string>? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetButtonTextsCore(element), (actual, expected1) => (actual?.SequenceEqual(expected1!) == true),
           message ?? $"Expected ButtonTexts to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitButtonTextsHasItem(string item, int? timeoutMs = null)
    {
        return RunWaitWithElement(item,
           element => GetButtonTextsCore(element)?.Contains(item!) == true,
           timeoutMs);
    }

    public ContentDialog<TParent> AssertButtonTextsHasItem(string item, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement((bool?)true,
           element => (bool?)(GetButtonTextsCore(element)?.Contains(item!) == true), (actual, expected1) => (actual == expected1),
           message ?? $"Expected ButtonTextsHasItem to contain '{item}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitButtonTextsCount(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetButtonTextsCore(element)?.Count() == expected,
           timeoutMs);
    }

    public ContentDialog<TParent> AssertButtonTextsCount(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => (int?)(GetButtonTextsCore(element)?.Count()), (actual, expected1) => (actual == expected1),
           message ?? $"Expected ButtonTextsCount to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Message (GetMessage / WaitMessage / AssertMessage)

    public string? GetMessage(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetMessageCore(element), timeoutMs);
    }

    public bool WaitMessage(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetMessageCore(element) == expected,
           timeoutMs);
    }

    public ContentDialog<TParent> AssertMessage(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetMessageCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Message to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
