<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.Blazor</RootNamespace>
    <Description>Blazor UI testing automation using Playwright. Provides controls and page objects for Blazor Server and WebAssembly application testing.</Description>
    <PackageId>Brinell.Blazor</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brinell.Html\Brinell.Html.csproj" />
    <ProjectReference Include="..\Brinell.Html.Playwright\Brinell.Html.Playwright.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

</Project>
