<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.Blazor</RootNamespace>
    <AssemblyName>Brinell.Blazor</AssemblyName>
    <Description>Blazor platform implementation for Brinell UI Test Automation Framework</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brinell.Core\Brinell.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" />
    <PackageReference Include="Selenium.Support" />
  </ItemGroup>

</Project>
