using Brinell.Core;
using Brinell.Core.Interfaces;
using Brinell.Core.Locators;
using Brinell.Maui.Controls;
using Brinell.Maui.Controls.Base;
using Brinell.Maui.Interfaces;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls;


/// <summary>
/// MAUI Tab control for CommunityToolkit TabView navigation.
/// <para>
/// Uses AutomationId for reliable, fast element location (unlike Shell TabBar which requires XPath).
/// Implements element-passing optimization pattern from SPEC-015b.
/// </para>
/// <example>
/// XAML:
/// <code>
/// &lt;toolkit:TabView AutomationId="MainTabView"&gt;
///     &lt;toolkit:TabViewItem AutomationId="ContainersTab" Header="Containers"&gt;
///         &lt;ContentView ...&gt;
///     &lt;/toolkit:TabViewItem&gt;
/// &lt;/toolkit:TabView&gt;
/// </code>
/// 
/// Test Code:
/// <code>
/// var containersTab = new TabViewControl&lt;MainWindowPage&gt;(page, "ContainersTab");
/// containersTab.Click();
/// </code>
/// </example>
/// </summary>
/// <typeparam name="TScope">The scope type (typically a page object)</typeparam>

public partial class TabViewControl<TScope> : Brinell.Maui.Controls.Base.ClickableControlBase<TScope>, ITabControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Selected (IsSelected / WaitSelected / AssertSelected)

    public bool? IsSelected()
    {
        return IsSelectedCore(TryFindElement()) == true;
    }

    public bool WaitSelected(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsSelectedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertSelected(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsSelectedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Selected to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
