// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI BoxView control for displaying a simple colored rectangle.
/// BoxView is typically used as a visual element for layout purposes.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class BoxView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
