// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI Frame control for bordered containers with optional shadow styling.
/// Frame wraps content with a border, shadow, and background.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Frame<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
