using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI Grid container. Scopes searches to the grid's own subtree, so child controls
/// are found within the grid rather than page-wide.
/// </summary>
/// <remarks>
/// <para>
/// One type serves both a scoped and a nested grid: every inherited member returns the grid
/// itself, so there is no need for a separate parent-returning variant.
/// </para>
/// <para>
/// <b>Windows requires an automation handler.</b> A stock MAUI <c>Grid</c> maps to a
/// WinUI panel with no AutomationPeer, so its <c>AutomationId</c> is invisible to UI
/// Automation and this container will not resolve. The app under test must register the
/// Brinell automation handlers — see <c>samples/Brinell.Maui.AppSupport</c>, which can be
/// referenced as a project or copied into the app.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The grid type itself (self-referencing for fluent returns).</typeparam>

public partial class Grid<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : Grid<TParent, TSelf>
{

}
