using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI Grid container. Scopes searches to the grid's own subtree, so child controls
/// are found within the grid rather than page-wide.
/// </summary>
/// <remarks>
/// <para>
/// This replaces the former <c>Grid&lt;TScope&gt;</c> / <c>Grid&lt;TParent, TSelf&gt;</c>
/// pair. That split existed only because the old container base made a container's own
/// inherited members return the parent scope; with
/// <see cref="ContainerObjectBase{TParent, TSelf}"/> every member returns the grid, so
/// one type serves both uses.
/// </para>
/// <para>
/// <b>Windows requires an automation handler.</b> A stock MAUI <c>Grid</c> maps to a
/// WinUI panel with no AutomationPeer, so its <c>AutomationId</c> is invisible to UI
/// Automation and this container will not resolve. The app under test must register the
/// Brinell automation handlers — see <c>samples/Brinell.Maui.AppSupport</c>, which can be
/// referenced as a project or copied into the app.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The grid type itself (self-referencing for fluent returns).</typeparam>

public partial class Grid<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : Grid<TParent, TSelf>
{

}
