// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI IsoPaneView (TwoPaneView) control for dual-pane layouts on foldable devices.
/// IsoPaneView is used to display content across multiple panes on foldable screens.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class IsoPaneView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
