using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI RefreshView control: a container that refreshes its content when pulled down.
/// </summary>
/// <remarks>
/// <b>Not addressable on Windows.</b> RefreshView maps to the WinUI <c>RefreshContainer</c>,
/// whose automation peer cannot be overridden without collapsing the UIA tree. On Windows, drive
/// the bound command instead.
/// </remarks>
/// <typeparam name="TParent">The parent scope type.</typeparam>
/// <typeparam name="TSelf">The concrete container type.</typeparam>

public partial class RefreshView<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>,
    IRefreshableControlObject<TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : RefreshView<TParent, TSelf>
{
    #region Enabled (IsEnabled / WaitEnabled / AssertEnabled)

    public bool? IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsEnabledCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Enabled to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region PullToRefresh

    public TSelf PullToRefresh(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PullToRefreshCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Refreshing (IsRefreshing / WaitRefreshing / AssertRefreshing)

    public bool? IsRefreshing()
    {
        return IsRefreshingCore(TryFindElement()) == true;
    }

    public bool WaitRefreshing(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsRefreshingCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertRefreshing(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsRefreshingCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Refreshing to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
