// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI RefreshView control: a container that refreshes its content when pulled down.
/// </summary>
/// <remarks>
/// <para>
/// Refreshing is declared as a capability (<see cref="IRefreshableControlObject{TScope}"/>)
/// rather than inherited from a refreshable base class. C# allows one base class, and a
/// RefreshView wraps a scrollable child — a control that may well need both capabilities.
/// </para>
/// <para>
/// <b>Not addressable on Windows.</b> RefreshView maps to the WinUI
/// <c>RefreshContainer</c>, whose automation peer must not be overridden — doing so
/// collapses the entire UIA tree. Pull-to-refresh is a mobile gesture in any case; on
/// Windows, drive the bound command instead. These members exist for the planned
/// Android/iOS phase.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class RefreshView<TScope> : Base.ViewBase<TScope>, IRefreshableControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region PullToRefresh

    public TScope PullToRefresh(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PullToRefreshCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Refreshing (IsRefreshing / WaitRefreshing / AssertRefreshing)

    public bool? IsRefreshing()
    {
        return IsRefreshingCore(TryFindElement()) == true;
    }

    public bool WaitRefreshing(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsRefreshingCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertRefreshing(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsRefreshingCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Refreshing to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
