using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI ScrollView container. Scopes searches to the view's own subtree and adds
/// scrolling.
/// </summary>
/// <remarks>
/// <para>
/// A scrolling container needs both scroll behaviour and container scoping, and C# gives
/// one base class. Scoping wins the base slot — it is the reason to model a ScrollView as
/// a container at all — and the scroll mechanics are delegated to
/// <see cref="ScrollHelper"/>, which <see cref="CollectionObjectBase{TParent, TSelf, TItem}"/>
/// also uses.
/// </para>
/// <para>
/// Scrolling is UI Automation first, falling back to a pointer swipe only where pointer
/// input is permitted. The methods here report progress rather than throwing when
/// scrolling is not possible, because "cannot scroll further" is an ordinary outcome.
/// </para>
/// <para>
/// Unlike the other layout containers, <c>ScrollView</c> is addressable on Windows
/// without an automation handler.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The view type itself (self-referencing for fluent returns).</typeparam>

public partial class ScrollView<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : ScrollView<TParent, TSelf>
{
    #region ScrollForward

    public TSelf ScrollForward()
    {
        return RunDoWithElement(element => { ScrollForwardCore(element); });
    }

    #endregion
    #region ScrollBack

    public TSelf ScrollBack()
    {
        return RunDoWithElement(element => { ScrollBackCore(element); });
    }

    #endregion

}
