using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI ScrollView container. Scopes searches to the view's own subtree and adds
/// scrolling.
/// </summary>
/// <remarks>
/// Scrolling methods report progress rather than throwing when the content cannot scroll further.
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The view type itself (self-referencing for fluent returns).</typeparam>

public partial class ScrollView<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : ScrollView<TParent, TSelf>
{
    #region ScrollForward

    public TSelf ScrollForward()
    {
        return RunDoWithElement(element => { ScrollForwardCore(element); });
    }

    #endregion
    #region ScrollBack

    public TSelf ScrollBack()
    {
        return RunDoWithElement(element => { ScrollBackCore(element); });
    }

    #endregion

}
