using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI SwipeView control: a container whose content reveals actions when swiped.
/// </summary>
/// <remarks>
/// <para>
/// <b>Not addressable on Windows.</b> SwipeView maps to the WinUI <c>SwipeControl</c>, whose
/// automation peer cannot be overridden without collapsing the UIA tree, so these members cannot
/// find the control in a Windows test.
/// </para>
/// <para>
/// To swipe it on Windows anyway, call <c>IMauiDriver.PerformGesture(id, gesture)</c> with its
/// <c>AutomationId</c>.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type.</typeparam>
/// <typeparam name="TSelf">The concrete container type.</typeparam>

public partial class SwipeView<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>,
    ISwipeableControlObject<TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : SwipeView<TParent, TSelf>
{
    #region Enabled (IsEnabled / WaitEnabled / AssertEnabled)

    public bool? IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsEnabledCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Enabled to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SwipeLeft

    public TSelf SwipeLeft(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeLeftCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeRight

    public TSelf SwipeRight(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeRightCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeUp

    public TSelf SwipeUp(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeUpCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeDown

    public TSelf SwipeDown(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeDownCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Swipe

    public TSelf Swipe(int startX, int startY, int endX, int endY, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeCore(element, startX, startY, endX, endY, timeoutMs); }, timeoutMs);
    }

    #endregion

}
