using Brinell.Maui.Controls.Internal;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI SwipeView control: a container whose content reveals actions when swiped.
/// </summary>
/// <remarks>
/// <para>
/// Swiping is declared as a capability (<see cref="ISwipeableControlObject{TScope}"/>) and
/// delegated to <see cref="GestureHelper"/>, rather than inherited from a swipeable base
/// class. C# allows one base class, and a control may need swiping alongside another
/// capability; composing interfaces keeps that open.
/// </para>
/// <para>
/// <b>Not addressable on Windows.</b> SwipeView maps to the WinUI <c>SwipeControl</c>,
/// whose automation peer must not be overridden — doing so collapses the entire UIA tree.
/// Its <c>AutomationId</c> is therefore invisible and none of the members here can run in a
/// Windows test. They exist for the planned Android/iOS phase, where swipe is a native
/// gesture and the control is addressable.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class SwipeView<TScope> : Base.ViewBase<TScope>, ISwipeableControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SwipeLeft

    public TScope SwipeLeft(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeLeftCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeRight

    public TScope SwipeRight(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeRightCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeUp

    public TScope SwipeUp(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeUpCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeDown

    public TScope SwipeDown(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeDownCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Swipe

    public TScope Swipe(int startX, int startY, int endX, int endY, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeCore(element, startX, startY, endX, endY, timeoutMs); }, timeoutMs);
    }

    #endregion

}
