using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Container;


/// <summary>
/// MAUI SwipeView control: a container whose content reveals actions when swiped.
/// </summary>
/// <remarks>
/// <para>
/// <b>A container</b> (step 102, option B): it hosts content, so it is modelled the way
/// <c>ScrollView</c> and <c>Border</c> are - its children are found under it. It used to be a
/// view, which gave it no way to name what it holds.
/// </para>
/// <para>
/// Swiping is declared as a capability (<see cref="ISwipeableControlObject{TSelf}"/>) and
/// delegated to the element gesture extensions, rather than inherited from a swipeable base
/// class. C# allows one base class, and a control may need swiping alongside another
/// capability; composing interfaces keeps that open.
/// </para>
/// <para>
/// <b>Not addressable on Windows.</b> SwipeView maps to the WinUI <c>SwipeControl</c>, whose
/// automation peer must not be overridden — doing so collapses the entire UIA tree. Its
/// <c>AutomationId</c> is therefore invisible, and because every member here finds its element
/// first, none of them can run in a Windows test.
/// </para>
/// <para>
/// <b>The gesture still reaches it on Windows; the control object does not.</b> The bridge
/// publishes a separate element carrying the verb and is addressed by <c>AutomationId</c>, so
/// <c>IMauiDriver.PerformGesture(id, gesture)</c> works on a control nothing can find. Closing
/// that gap means members that do not look for an element at all, which is a change to what the
/// generator emits rather than to this file — see step 19 in <c>.my/extension/steps.md</c>.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type.</typeparam>
/// <typeparam name="TSelf">The concrete container type.</typeparam>

public partial class SwipeView<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>,
    ISwipeableControlObject<TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : SwipeView<TParent, TSelf>
{
    #region Enabled (IsEnabled / WaitEnabled / AssertEnabled)

    public bool? IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsEnabledCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Enabled to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SwipeLeft

    public TSelf SwipeLeft(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeLeftCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeRight

    public TSelf SwipeRight(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeRightCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeUp

    public TSelf SwipeUp(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeUpCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SwipeDown

    public TSelf SwipeDown(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeDownCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Swipe

    public TSelf Swipe(int startX, int startY, int endX, int endY, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SwipeCore(element, startX, startY, endX, endY, timeoutMs); }, timeoutMs);
    }

    #endregion

}
