// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Toggle;


/// <summary>
/// MAUI Switch control with On/Off terminology.
/// Provides IsOn, TurnOn, TurnOff alias methods in addition to inherited toggle methods.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Switch<TScope> : Base.ToggleControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region On (IsOn / WaitOn / AssertOn)

    public bool? IsOn()
    {
        return IsOnCore(TryFindElement()) == true;
    }

    public bool WaitOn(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsOnCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertOn(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsOnCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected On to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SetOn

    public TScope SetOn(bool? on, int? timeoutMs = null)
    {
        return RunSetWithElement(on, element => { SetOnCore(element, on, timeoutMs); }, timeoutMs);
    }

    #endregion

}
