// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Display;


/// <summary>
/// MAUI ActivityIndicator control for displaying loading/busy state.
/// Provides IsRunning(), WaitRunning(), and running state assertions.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class ActivityIndicator<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Running (IsRunning / WaitRunning / AssertRunning)

    public bool? IsRunning()
    {
        return IsRunningCore(TryFindElement()) == true;
    }

    public bool WaitRunning(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsRunningCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertRunning(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsRunningCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Running to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
