// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Display;


/// <summary>
/// MAUI Image control for displaying images with source and dimension access.
/// Provides IsLoaded(), GetSource(), GetWidth(), GetHeight(), and image assertions.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Image<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Source (GetSource / WaitSource / AssertSource)

    public string? GetSource(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetSourceCore(element), timeoutMs);
    }

    public bool? WaitSource(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSourceCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertSource(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSourceCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Source to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Loaded (IsLoaded / WaitLoaded / AssertLoaded)

    public bool? IsLoaded()
    {
        return IsLoadedCore(TryFindElement()) == true;
    }

    public bool WaitLoaded(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsLoadedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertLoaded(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsLoadedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Loaded to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Width (GetWidth / WaitWidth / AssertWidth)

    public int? GetWidth(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetWidthCore(element), timeoutMs);
    }

    public bool? WaitWidth(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetWidthCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertWidth(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetWidthCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Width to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Height (GetHeight / WaitHeight / AssertHeight)

    public int? GetHeight(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetHeightCore(element), timeoutMs);
    }

    public bool? WaitHeight(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetHeightCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertHeight(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetHeightCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Height to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
