// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Display;


/// <summary>
/// MAUI ProgressBar control for displaying progress values (0-1).
/// Provides GetProgress(), IsIndeterminate(), and progress assertions.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class ProgressBar<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Progress (GetProgress / WaitProgress / AssertProgress)

    public double? GetProgress(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetProgressCore(element), timeoutMs);
    }

    public bool? WaitProgress(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetProgressCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertProgress(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetProgressCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Progress to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Indeterminate (IsIndeterminate / WaitIndeterminate / AssertIndeterminate)

    public bool? IsIndeterminate()
    {
        return IsIndeterminateCore(TryFindElement()) == true;
    }

    public bool WaitIndeterminate(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsIndeterminateCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertIndeterminate(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsIndeterminateCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Indeterminate to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
