// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Display;


/// <summary>
/// MAUI TitleBar control for customizing window title bar appearance and behavior.
/// TitleBar is used to customize the window decoration and is platform-specific.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TitleBar<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Text (GetText / WaitText / AssertText)

    public string? GetText(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTextCore(element), timeoutMs);
    }

    public bool? WaitText(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertText(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Text to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextContains(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.Contains(expected!) == true,
           timeoutMs);
    }

    public TScope AssertTextContains(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.Contains(expected1!) == true),
           message ?? $"Expected TextContains to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextStartsWith(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.StartsWith(expected!) == true,
           timeoutMs);
    }

    public TScope AssertTextStartsWith(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.StartsWith(expected1!) == true),
           message ?? $"Expected TextStartsWith to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextEndsWith(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element)?.EndsWith(expected!) == true,
           timeoutMs);
    }

    public TScope AssertTextEndsWith(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual?.EndsWith(expected1!) == true),
           message ?? $"Expected TextEndsWith to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitTextEmpty(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => string.IsNullOrEmpty(GetTextCore(element)) == expected,
           timeoutMs);
    }

    public TScope AssertTextEmpty(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => (bool?)string.IsNullOrEmpty(GetTextCore(element)), (actual, expected1) => (actual == expected1),
           message ?? $"Expected TextEmpty to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
