// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Shell FlyoutItem control for navigation.
/// Uses XPath with @Name (Title) instead of AccessibilityId because
/// FlyoutItem's AutomationId doesn't propagate to the Windows UI Automation tree.
/// Inherits from ClickableControlBase for click functionality.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class FlyoutItem<TScope> : Base.ClickableControlBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
