// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Menu/FlyoutMenu control for navigation menus.
/// Provides methods for menu item access and interaction.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Menu<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Open

    public TScope Open(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { OpenCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region ClickMenuItem

    public TScope ClickMenuItem(Locator itemLocator, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickMenuItemCore(element, itemLocator, timeoutMs); }, timeoutMs);
    }

    #endregion

}
