using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Menu: a collection of <see cref="MenuItem{TParent}"/> with a trigger that reveals them.
/// </summary>
/// <remarks>
/// <para>
/// The menu's root is the menu as a whole, so the trigger, the items and any chrome are all
/// found inside it and a lookup never escapes to the page:
/// </para>
/// <code>
/// Menu.Open();
/// Menu.AssertOpen();
/// Menu["New"].Click();
/// </code>
/// <para>
/// A menu whose root <i>is</i> its trigger and item host - a bar that is always showing its
/// items - needs neither extra locator and behaves as it did before.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The containing scope type.</typeparam>

public partial class Menu<TParent> : CollectionObjectBase<TParent, Menu<TParent>, MenuItem<TParent>>
    where TParent : IMauiScope<TParent>
{
    #region Open

    public Menu<TParent> Open(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { OpenCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Open (IsOpen / WaitOpen / AssertOpen)

    public bool? IsOpen()
    {
        return IsOpenCore(TryFindElement()) == true;
    }

    public bool WaitOpen(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsOpenCore(element) == expected!.Value,
           timeoutMs);
    }

    public Menu<TParent> AssertOpen(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsOpenCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Open to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
