using Brinell.Core.Interfaces;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Shell control for managing TabBar navigation and shell state.
/// Provides access to individual tabs and shell-level operations.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Shell<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
