using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// A MAUI Shell's flyout: a collection of <see cref="ShellFlyoutItem{TParent}"/>, with the
/// affordance that reveals them.
/// </summary>
/// <remarks>
/// A flyout is open when its host is visible and holds items: Windows keeps a closed pane's
/// items in the tree, and Android's host is always visible.
/// </remarks>
/// <typeparam name="TParent">The scope the shell belongs to.</typeparam>

public partial class ShellFlyout<TParent> : CollectionObjectBase<TParent, ShellFlyout<TParent>, ShellFlyoutItem<TParent>>
    where TParent : IMauiScope<TParent>
{
    #region Open (IsOpen / WaitOpen / AssertOpen)

    public bool? IsOpen()
    {
        return IsOpenCore(TryFindElement()) == true;
    }

    public bool WaitOpen(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsOpenCore(element) == expected!.Value,
           timeoutMs);
    }

    public ShellFlyout<TParent> AssertOpen(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsOpenCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Open to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
