using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// A MAUI Shell's flyout: a collection of <see cref="ShellFlyoutItem{TParent}"/>, with the
/// affordance that reveals them.
/// </summary>
/// <remarks>
/// A flyout is open when its host is visible <b>and</b> holds items. Neither half is enough on
/// its own: Windows creates its pane on first opening and then keeps it hidden with its items
/// still in the tree, so items alone would read as open forever; Android's host is the app's
/// content frame, always visible, and it is the items that come and go. Each half was measured
/// on the platform that needs it.
/// <para>
/// Asking whether the <i>items</i> are visible looks like the tidier rule and is not: Windows
/// hosts an open pane in a window of its own, where its items report themselves off-screen.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The scope the shell belongs to.</typeparam>

public partial class ShellFlyout<TParent> : CollectionObjectBase<TParent, ShellFlyout<TParent>, ShellFlyoutItem<TParent>>
    where TParent : IMauiScope<TParent>
{
    #region Open (IsOpen / WaitOpen / AssertOpen)

    public bool? IsOpen()
    {
        return IsOpenCore(TryFindElement()) == true;
    }

    public bool WaitOpen(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsOpenCore(element) == expected!.Value,
           timeoutMs);
    }

    public ShellFlyout<TParent> AssertOpen(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsOpenCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Open to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
