using Brinell.Core.Interfaces;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Tab control for Shell TabBar navigation.
/// Tabs are rendered as ListItem elements with @Name attribute.
/// Inherits from ClickableControlBase for click functionality.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Tab<TScope> : Base.ClickableControlBase<TScope>, ITabControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Selected (IsSelected / WaitSelected / AssertSelected)

    public bool? IsSelected()
    {
        return IsSelectedCore(TryFindElement()) == true;
    }

    public bool WaitSelected(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsSelectedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertSelected(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsSelectedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Selected to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
