// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// One tab in a <see cref="TabMenu{TParent}"/>.
/// </summary>
/// <remarks>
/// A tab is not one element: it is a surface holding a button and a caption, and which of
/// those carries the command or the text differs by platform. The tab is rooted at the
/// surface, so the item scopes both, and each member below reaches for the part that knows.
/// </remarks>
/// <typeparam name="TParent">The scope the tab menu belongs to.</typeparam>

public partial class TabItem<TParent> : Base.SelectableItemBase<TabMenu<TParent>, TabItem<TParent>>
    where TParent : IMauiScope<TParent>
{

}
