using Brinell.Maui.Configuration;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// Shared MAUI bottom tab menu control.
/// Uses invokable tab button surfaces when available and avoids pointer-only fallbacks.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TabMenu<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
