using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI tab bar: a collection of <see cref="TabItem{TParent}"/>.
/// </summary>
/// <remarks>
/// <para>
/// A Brinell composite rather than a stock MAUI control - see <see cref="TabMenuMarkup"/> for
/// the ids it expects. Each tab is one item, rooted at the surface that holds that tab's
/// button and caption:
/// </para>
/// <code>
/// Tabs["Search"].Click();
/// Tabs.AssertItemCount(3);
/// Tabs["Search"].AssertSelected();
/// </code>
/// <para>
/// This replaces a hand-written search that fetched three parallel lists - captions, buttons
/// and tab surfaces - and paired them by position, which no other collection could reuse and
/// which broke silently if one list came back shorter than the others.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The containing scope type.</typeparam>

public partial class TabMenu<TParent> : CollectionObjectBase<TParent, TabMenu<TParent>, TabItem<TParent>>
    where TParent : IMauiScope<TParent>
{

}
