using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Toolbar: a collection of <see cref="ToolbarItem{TParent}"/>, plus whatever else the
/// bar itself shows.
/// </summary>
/// <remarks>
/// <para>
/// Items are addressed on the toolbar and answered by an object:
/// <c>Toolbar["Save"].Click()</c>, <c>Toolbar["Save"].AssertEnabled()</c>,
/// <c>Toolbar.AssertItemCount(3)</c>. The string key is the item's caption - see
/// <see cref="CollectionObjectBase{TParent, TSelf, TItem}.MatchesKey"/>.
/// </para>
/// <para>
/// Being a container, the toolbar also scopes controls of its own, so an item with a unique
/// automation id can still be reached as a control:
/// <c>new Button&lt;Toolbar&lt;MyPage&gt;&gt;(toolbar, "ToolbarSaveButton")</c>. Both routes
/// search within the toolbar, never the page.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The containing scope type.</typeparam>

public partial class Toolbar<TParent> : CollectionObjectBase<TParent, Toolbar<TParent>, ToolbarItem<TParent>>
    where TParent : IMauiScope<TParent>
{
    #region Title (GetTitle / WaitTitle / AssertTitle)

    public string? GetTitle(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTitleCore(element), timeoutMs);
    }

    public bool? WaitTitle(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTitleCore(element) == expected,
           timeoutMs);
    }

    public Toolbar<TParent> AssertTitle(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTitleCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Title to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
