// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Navigation;


/// <summary>
/// MAUI Toolbar control for app navigation bars and toolbars.
/// Provides access to toolbar items and navigation actions.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Toolbar<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region ClickToolbarItem

    public TScope ClickToolbarItem(Locator itemLocator, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickToolbarItemCore(element, itemLocator, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Title (GetTitle / WaitTitle / AssertTitle)

    public string? GetTitle(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTitleCore(element), timeoutMs);
    }

    public bool? WaitTitle(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTitleCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertTitle(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTitleCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Title to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
