using Brinell.Core.Interfaces;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Extensions.Controls.Container;


/// <summary>
/// MAUI Expander control: a disclosure container that shows or hides its content.
/// </summary>
/// <remarks>
/// Derives from <c>Base.ClickableControlBase</c> because an expander is fundamentally
/// clickable — clicking the header is how it toggles. Expanding is declared as a capability
/// (<see cref="IExpandableControlObject{TScope}"/>) rather than inherited, since C# allows
/// one base class and expanding composes with clicking rather than replacing it.
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Expander<TScope> : Brinell.Maui.Controls.Base.ClickableControlBase<TScope>,
    IExpandableControlObject<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Expand

    public TScope Expand(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ExpandCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Collapse

    public TScope Collapse(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { CollapseCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region ToggleExpanded

    public TScope ToggleExpanded(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ToggleExpandedCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Expanded (IsExpanded / WaitExpanded / AssertExpanded)

    public bool? IsExpanded()
    {
        return IsExpandedCore(TryFindElement()) == true;
    }

    public bool WaitExpanded(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsExpandedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertExpanded(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsExpandedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Expanded to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
