// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Buttons;


/// <summary>
/// MAUI Button control with click capability and fluent method chaining.
/// Inherits from ClickableControlBase which provides all click functionality.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Button<TScope> : Base.ClickableControlBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
