// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Buttons;


/// <summary>
/// MAUI ImageButton control for clickable images.
/// Combines clickable behavior with image properties.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class ImageButton<TScope> : Base.ClickableControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Source (GetSource / WaitSource / AssertSource)

    public string? GetSource(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetSourceCore(element), timeoutMs);
    }

    public bool? WaitSource(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSourceCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertSource(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSourceCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Source to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Aspect (GetAspect / WaitAspect / AssertAspect)

    public string? GetAspect(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetAspectCore(element), timeoutMs);
    }

    public bool? WaitAspect(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetAspectCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertAspect(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetAspectCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Aspect to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
