// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Media;


/// <summary>
/// MAUI BlazorWebView control for hosting Blazor applications within MAUI.
/// BlazorWebView enables running Blazor apps as part of a MAUI application.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class BlazorWebView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
