// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Media;


/// <summary>
/// MAUI HybridWebView control for hybrid web content with C#/JavaScript interop (new in MAUI 9+).
/// HybridWebView enables bidirectional communication between managed code and web content.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class HybridWebView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
