// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Media;


/// <summary>
/// MAUI MediaElement control for audio/video playback.
/// Provides methods for media playback control and state inspection.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class MediaElement<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Playing (IsPlaying / WaitPlaying / AssertPlaying)

    public bool? IsPlaying()
    {
        return IsPlayingCore(TryFindElement()) == true;
    }

    public bool WaitPlaying(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsPlayingCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertPlaying(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsPlayingCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Playing to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Paused (IsPaused / WaitPaused / AssertPaused)

    public bool? IsPaused()
    {
        return IsPausedCore(TryFindElement()) == true;
    }

    public bool WaitPaused(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsPausedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertPaused(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsPausedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Paused to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Muted (IsMuted / WaitMuted / AssertMuted)

    public bool? IsMuted()
    {
        return IsMutedCore(TryFindElement()) == true;
    }

    public bool WaitMuted(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsMutedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertMuted(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsMutedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Muted to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region PlaybackState (GetPlaybackState / WaitPlaybackState / AssertPlaybackState)

    public string? GetPlaybackState(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPlaybackStateCore(element), timeoutMs);
    }

    public bool? WaitPlaybackState(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPlaybackStateCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertPlaybackState(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPlaybackStateCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected PlaybackState to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Position (GetPosition / WaitPosition / AssertPosition)

    public double? GetPosition(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPositionCore(element), timeoutMs);
    }

    public bool? WaitPosition(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPositionCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertPosition(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPositionCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Position to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Duration (GetDuration / WaitDuration / AssertDuration)

    public double? GetDuration(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetDurationCore(element), timeoutMs);
    }

    public bool? WaitDuration(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetDurationCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertDuration(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetDurationCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Duration to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Volume (GetVolume / WaitVolume / AssertVolume)

    public double? GetVolume(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetVolumeCore(element), timeoutMs);
    }

    public bool? WaitVolume(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetVolumeCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertVolume(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetVolumeCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Volume to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
