// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Media;


/// <summary>
/// MAUI MediaElement control for audio/video playback.
/// Provides methods for media playback control and state inspection.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class MediaElement<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
