// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Media;


/// <summary>
/// MAUI WebView control for displaying web content.
/// Provides methods for URL navigation and web content interaction.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class WebView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Url (GetUrl / WaitUrl / AssertUrl)

    public string? GetUrl(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetUrlCore(element), timeoutMs);
    }

    public bool? WaitUrl(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetUrlCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertUrl(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetUrlCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Url to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitUrlContains(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetUrlCore(element)?.Contains(expected!) == true,
           timeoutMs);
    }

    public TScope AssertUrlContains(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetUrlCore(element), (actual, expected1) => (actual?.Contains(expected1!) == true),
           message ?? $"Expected UrlContains to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region PageTitle (GetPageTitle / WaitPageTitle / AssertPageTitle)

    public string? GetPageTitle(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPageTitleCore(element), timeoutMs);
    }

    public bool? WaitPageTitle(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPageTitleCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertPageTitle(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPageTitleCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected PageTitle to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool? WaitPageTitleContains(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPageTitleCore(element)?.Contains(expected!) == true,
           timeoutMs);
    }

    public TScope AssertPageTitleContains(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPageTitleCore(element), (actual, expected1) => (actual?.Contains(expected1!) == true),
           message ?? $"Expected PageTitleContains to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region CanGoBack (IsCanGoBack / WaitCanGoBack / AssertCanGoBack)

    public bool? IsCanGoBack()
    {
        return IsCanGoBackCore(TryFindElement()) == true;
    }

    public bool WaitCanGoBack(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsCanGoBackCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertCanGoBack(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsCanGoBackCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected CanGoBack to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region CanGoForward (IsCanGoForward / WaitCanGoForward / AssertCanGoForward)

    public bool? IsCanGoForward()
    {
        return IsCanGoForwardCore(TryFindElement()) == true;
    }

    public bool WaitCanGoForward(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsCanGoForwardCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertCanGoForward(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsCanGoForwardCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected CanGoForward to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
