<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.WinForms.Uat.Tests</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\srcnew\Brinell.Uat\Brinell.Uat.csproj" />
    <ProjectReference Include="..\Brinell.WinForms.UITests\Brinell.WinForms.UITests.csproj" />
    <ProjectReference Include="..\..\samples\Brinell.Samples.WinForms.App\Brinell.Samples.WinForms.App.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="uat.config.md" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Scenarios\**\*.uat.md" CopyToOutputDirectory="PreserveNewest" />
    <None Update="TestSettings\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="BuildWinFormsSampleApp" BeforeTargets="Build">
    <MSBuild Projects="..\..\samples\Brinell.Samples.WinForms.App\Brinell.Samples.WinForms.App.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
  </Target>

</Project>
