using Brinell.Generator.Models;
using Brinell.Generator.Writers;

namespace Brinell.Generator.Generation;

/// <summary>
/// Assembles the complete generated C# file (usings, namespace, partial class,
/// and generated members) using <see cref="CsWriter"/>.
/// </summary>
public class ControlObjectBuilder
{
    /// <summary>
    /// Builds a complete C# file with usings, namespace, and the generated partial class.
    /// </summary>
    /// <param name="context">The analyzed ControlObject context.</param>
    /// <param name="members">The generated member code strings.</param>
    /// <param name="includeHeader">Whether to include a generated code header comment.</param>
    /// <returns>The complete C# file content.</returns>
    public string BuildCompilationUnit(
        ControlObjectContext context,
        List<string> members,
        bool includeHeader = true)
    {
        var writer = new CsWriter(0); // Start with no indentation for file level

        // Add header comment
        if (includeHeader)
        {
            writer.WriteLine("// <auto-generated />");
            writer.WriteLine("// This file was generated by Brinell.Generator and should not be edited manually.");
            writer.WriteLine();
        }

        // Roslyn treats <auto-generated /> files as outside the nullable context,
        // so the annotations copied from the template need it turned back on.
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        // Add using statements
        foreach (var usingDirective in context.Usings)
        {
            writer.AddUsing(usingDirective);
        }

        // Add namespace (file-scoped)
        if (!string.IsNullOrEmpty(context.Namespace))
        {
            writer.WriteLine($"namespace {context.Namespace};");
            writer.WriteLine();
        }

        // Write class declaration with original signature/documentation if available
        var classDecl = context.ClassDeclaration;
        if (classDecl != null)
        {
            var leadingTrivia = classDecl.GetLeadingTrivia();
            if (leadingTrivia.Any())
            {
                writer.WriteLines(leadingTrivia.ToString());
            }

            var classSignature = ReconstructClassSignature(classDecl);
            writer.WriteLine(classSignature);
        }
        else
        {
            writer.WriteLine($"public partial class {context.ContainingTypeName}");
        }

        writer.Open(); // Opens the class and increments indentation

        // Add all generated members (each member string has newlines that need proper indentation)
        var combinedMembers = string.Concat(members);
        writer.WriteLines(combinedMembers);

        writer.Close(); // Closes the class

        return writer.ToString();
    }

    /// <summary>
    /// Reconstructs the class signature preserving inheritance, generics, and constraints.
    /// </summary>
    private string ReconstructClassSignature(Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax classDecl)
    {
        var modifiers = classDecl.Modifiers;

        // Check if 'partial' is already present
        bool hasPartial = modifiers.Any(m => m.Text == "partial");

        // Build modifier list
        var modifierList = new List<string>();
        foreach (var modifier in modifiers)
        {
            modifierList.Add(modifier.Text);
        }

        // Add 'partial' if not present
        if (!hasPartial)
        {
            modifierList.Add("partial");
        }

        // Build the signature
        var signature = string.Join(" ", modifierList);
        if (!string.IsNullOrEmpty(signature))
        {
            signature += " ";
        }

        // Add class keyword and name
        signature += "class " + classDecl.Identifier.Text;

        // Add generic type parameters
        if (classDecl.TypeParameterList != null)
        {
            signature += classDecl.TypeParameterList.ToString();
        }

        // Add base types
        if (classDecl.BaseList != null)
        {
            signature += " " + classDecl.BaseList.ToString();
        }

        // Add generic constraints on separate lines
        var constraints = classDecl.ConstraintClauses;
        if (constraints.Any())
        {
            foreach (var constraint in constraints)
            {
                signature += "\n    " + constraint.ToString();
            }
        }

        return signature;
    }
}
