using Brinell.Generator.Writers;

namespace Brinell.Generator.Generation;

/// <summary>
/// Generates wrapper methods and builds the complete C# file content using CsWriter.
/// </summary>
public class WrapperGenerator
{
    /// <summary>
    /// Generates wrapper methods for all extracted methods using the provided handlers.
    /// </summary>
    /// <param name="methods">The extracted method information.</param>
    /// <param name="handlers">The method handlers that can generate wrappers.</param>
    /// <param name="containingTypeName">The name of the containing type (for return types).</param>
    /// <param name="typeParameters">Generic type parameters (e.g., "&lt;TScope&gt;").</param>
    /// <returns>List of generated wrapper method code strings.</returns>
    public List<string> GenerateWrapperMethods(
        List<Models.MethodInfo> methods,
        IEnumerable<IMethodHandler> handlers,
        string containingTypeName,
        string typeParameters)
    {
        var wrapperMethods = new List<string>();
        var handlerList = handlers.ToList();

        foreach (var method in methods)
        {
            foreach (var handler in handlerList)
            {
                var wrapper = handler.GenerateWrapper(method, containingTypeName, typeParameters);
                wrapperMethods.Add(wrapper);
                break; // Use first matching handler
            }
        }

        return wrapperMethods;
    }

    /// <summary>
    /// Builds a complete C# file with usings, namespace, and generated class.
    /// </summary>
    /// <param name="className">The name of the generated class.</param>
    /// <param name="wrapperMethods">The generated wrapper methods.</param>
    /// <param name="namespace">The namespace (null for no namespace).</param>
    /// <param name="usings">Using directives to include.</param>
    /// <param name="includeHeader">Whether to include a generated code header comment.</param>
    /// <param name="classDecl">The original class declaration to preserve signature and documentation.</param>
    /// <returns>The complete C# file content.</returns>
    public string BuildCompilationUnit(
        string className,
        List<string> wrapperMethods,
        string? @namespace,
        List<string> usings,
        bool includeHeader = true,
        Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax? classDecl = null)
    {
        var writer = new CsWriter(0); // Start with no indentation for file level

        // Add header comment
        if (includeHeader)
        {
            writer.WriteLine("// <auto-generated />");
            writer.WriteLine("// This file was generated by Brinell.Generator and should not be edited manually.");
            writer.WriteLine();
        }

        // Add using statements
        foreach (var usingDirective in usings)
        {
            writer.AddUsing(usingDirective);
        }

        // Add namespace (file-scoped)
        if (!string.IsNullOrEmpty(@namespace))
        {
            writer.WriteLine($"namespace {@namespace};");
            writer.WriteLine();
        }

        // Write class declaration with original signature/documentation if available
        if (classDecl != null)
        {
            // Include the original class declaration's trivia (documentation) and signature
            var leadingTrivia = classDecl.GetLeadingTrivia();
            if (leadingTrivia.Any())
            {
                writer.WriteLines(leadingTrivia.ToString());
            }

            // Reconstruct class declaration with original inheritance and generics
            var classSignature = ReconstructClassSignature(classDecl);
            writer.WriteLine(classSignature);
        }
        else
        {
            writer.WriteLine($"public partial class {className}");
        }

        writer.Open(); // Opens the class and increments indentation

        // Add all wrapper methods (each method string has newlines that need proper indentation)
        var combinedMethods = string.Concat(wrapperMethods);
        writer.WriteLines(combinedMethods);

        writer.Close(); // Closes the class

        return writer.ToString();
    }

    /// <summary>
    /// Reconstructs the class signature preserving inheritance, generics, and constraints.
    /// </summary>
    private string ReconstructClassSignature(Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax classDecl)
    {
        var modifiers = classDecl.Modifiers;
        
        // Check if 'partial' is already present
        bool hasPartial = modifiers.Any(m => m.Text == "partial");

        // Build modifier list
        var modifierList = new List<string>();
        foreach (var modifier in modifiers)
        {
            modifierList.Add(modifier.Text);
        }

        // Add 'partial' if not present
        if (!hasPartial)
        {
            modifierList.Add("partial");
        }

        // Build the signature
        var signature = string.Join(" ", modifierList);
        if (!string.IsNullOrEmpty(signature))
        {
            signature += " ";
        }
        
        // Add class keyword and name
        signature += "class " + classDecl.Identifier.Text;

        // Add generic type parameters
        if (classDecl.TypeParameterList != null)
        {
            signature += classDecl.TypeParameterList.ToString();
        }

        // Add base types
        if (classDecl.BaseList != null)
        {
            signature += " " + classDecl.BaseList.ToString();
        }

        // Add generic constraints on separate lines
        var constraints = classDecl.ConstraintClauses;
        if (constraints.Any())
        {
            foreach (var constraint in constraints)
            {
                signature += "\n    " + constraint.ToString();
            }
        }

        return signature;
    }
}
