<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.Presenter.Uat.Tests</RootNamespace>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\srcnew\Brinell.Uat\Brinell.Uat.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Maui\Brinell.Maui.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Maui.Extensions\Brinell.Maui.Extensions.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Maui.FlaUI\Brinell.Maui.FlaUI.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Presenter\Brinell.Presenter.csproj" />
    <ProjectReference Include="..\Brinell.Maui.UITests\Brinell.Maui.UITests.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="uat.config.md" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Scenarios\**\*.uat.md" CopyToOutputDirectory="PreserveNewest" />
    <None Update="TestSettings\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="BuildPresenterSampleAut" BeforeTargets="Build">
    <MSBuild Projects="..\..\samples\Brinell.Samples.Maui.App\Brinell.Samples.Maui.App.csproj" Targets="Build" Properties="Configuration=$(Configuration);TargetFramework=net10.0-windows10.0.19041.0" />
  </Target>

</Project>
