global using Xunit;
global using Brinell.Core.Abstractions;
global using Brinell.Core.Interfaces;
global using Brinell.Core.Locators;
global using Brinell.Html.Context;
global using Brinell.Html.Controls;
global using Brinell.Html.Interfaces;
global using Brinell.Html.Pages;
global using Brinell.Html.Playwright;
