using Microsoft.CodeAnalysis.CSharp;
using Brinell.Generator.Generators;
using Brinell.Generator.Models;
using Brinell.Generator.Tests.Fixtures;

namespace Brinell.Generator.Tests;

public class ControlObjectGeneratorTests
{
    private static ControlObjectGenerator CreateGenerator() => ControlObjectGenerator.CreateDefault();

    private static GeneratorOptions Options(string? className = null) => new()
    {
        IncludeGeneratedHeader = true,
        TargetClassName = className
    };

    [Fact]
    public void GeneratesValidCSharpFromSimpleClass()
    {
        // Arrange
        var generator = CreateGenerator();

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options());

        // Assert
        Assert.NotEmpty(generatedCode);

        // Verify the output is valid C# by parsing it
        var tree = CSharpSyntaxTree.ParseText(generatedCode);
        var root = tree.GetRoot();
        Assert.NotNull(root);

        // Verify it contains the wrapper method
        Assert.Contains("public TScope Click", generatedCode);
        Assert.Contains("RunDoWithElement", generatedCode);
    }

    [Fact]
    public void GeneratesAutoGeneratedHeader()
    {
        var generator = CreateGenerator();

        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options());

        Assert.Contains("auto-generated", generatedCode, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GeneratesPartialClass()
    {
        var generator = CreateGenerator();

        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options());

        Assert.Contains("partial class", generatedCode);
    }

    [Fact]
    public void PreservesGenericTypeParameters()
    {
        var generator = CreateGenerator();

        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options());

        Assert.Contains("<TScope>", generatedCode);
        Assert.Contains("where TScope", generatedCode);
    }

    [Fact]
    public void PreservesNamespace()
    {
        var generator = CreateGenerator();

        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options());

        Assert.Contains("namespace Brinell.Maui.Controls", generatedCode);
    }

    [Fact]
    public void GeneratesMultipleMethods()
    {
        var generator = CreateGenerator();

        var generatedCode = generator.Generate(SampleCodeFixtures.MultiMethodClass, Options());

        Assert.Contains("public TScope Click", generatedCode);
        Assert.Contains("public TScope Hover", generatedCode);
    }

    [Fact]
    public void HandlesEmptyMethodList()
    {
        var generator = CreateGenerator();

        var generatedCode = generator.Generate(SampleCodeFixtures.NoMethodsClass, Options());

        Assert.NotEmpty(generatedCode);
        Assert.Contains("namespace Brinell.Maui.Controls", generatedCode);
        // No wrapper methods should be generated
        Assert.DoesNotContain("public TScope", generatedCode);
    }

    [Fact]
    public void ThrowsWhenClassNotFound()
    {
        var generator = CreateGenerator();

        var ex = Assert.Throws<InvalidOperationException>(() =>
            generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options("NonExistentClass")));

        Assert.Contains("NonExistentClass", ex.Message);
    }

    [Fact]
    public void ThrowsWhenNoGeneratorsRegistered()
    {
        var generator = new ControlObjectGenerator();

        Assert.Throws<InvalidOperationException>(() =>
            generator.Generate(SampleCodeFixtures.SimpleClickableClass, Options()));
    }

    [Fact]
    public void RegisterReturnsSameInstanceForChaining()
    {
        var generator = new ControlObjectGenerator();

        var returned = generator.Register(new ActionGenerator());

        Assert.Same(generator, returned);
    }

    [Fact]
    public void GeneratesBothActionAndStateMembersForMixedControl()
    {
        // Arrange
        var generator = CreateGenerator();

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.MixedControlClass, Options());

        // Assert - action wrapper
        Assert.Contains("public TScope Click", generatedCode);
        Assert.Contains("RunDoWithElement", generatedCode);

        // Assert - Is/Wait/Assert trio
        Assert.Contains("public bool? IsVisible()", generatedCode);
        Assert.Contains("public bool WaitVisible(bool? expected = true, int? timeoutMs = null)", generatedCode);
        Assert.Contains("public TScope AssertVisible(bool? expected = true, string? message = null, int? timeoutMs = null)", generatedCode);
    }

    [Fact]
    public void IsCoreMethod_HandledByIsWaitAssertGenerator_NotAction()
    {
        // Arrange - registration order: IsWaitAssert first, then Action.
        var generator = CreateGenerator();

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.MixedControlClass, Options());

        // Assert - IsVisibleCore must not produce an action wrapper "public TScope Visible(...)"
        Assert.DoesNotContain("public TScope Visible(", generatedCode);
    }

    [Fact]
    public void OnlyActionGenerator_SkipsIsCoreMethods()
    {
        // Arrange - Action generator alone must not capture Is*Core state queries.
        var generator = new ControlObjectGenerator().Register(new ActionGenerator());

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.MixedControlClass, Options());

        // Assert
        Assert.Contains("public TScope Click", generatedCode);
        Assert.DoesNotContain("public TScope Visible(", generatedCode);
        Assert.DoesNotContain("IsVisible()", generatedCode);
    }

    [Fact]
    public void OnlyIsWaitAssertGenerator_SkipsActionMethods()
    {
        // Arrange
        var generator = new ControlObjectGenerator().Register(new IsWaitAssertGenerator());

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.MixedControlClass, Options());

        // Assert
        Assert.Contains("public bool? IsVisible()", generatedCode);
        Assert.DoesNotContain("public TScope Click", generatedCode);
    }
}
