using Microsoft.CodeAnalysis.CSharp;
using Brinell.Generator.Handlers;
using Brinell.Generator.Models;
using Brinell.Generator.Tests.Fixtures;

namespace Brinell.Generator.Tests;

public class MethodWrapperGeneratorTests
{
    [Fact]
    public void GeneratesValidCSharpFromSimpleClass()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, options);

        // Assert
        Assert.NotEmpty(generatedCode);
        
        // Verify the output is valid C# by parsing it
        var tree = CSharpSyntaxTree.ParseText(generatedCode);
        var root = tree.GetRoot();
        Assert.NotNull(root);
        
        // Verify it contains the wrapper method
        Assert.Contains("public TScope Click", generatedCode);
        Assert.Contains("RunDoWithElement", generatedCode);
    }

    [Fact]
    public void GeneratesAutoGeneratedHeader()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, options);

        // Assert
        Assert.Contains("auto-generated", generatedCode, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GeneratesPartialClass()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, options);

        // Assert
        Assert.Contains("partial class", generatedCode);
    }

    [Fact]
    public void PreservesGenericTypeParameters()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, options);

        // Assert
        Assert.Contains("<TScope>", generatedCode);
        Assert.Contains("where TScope", generatedCode);
    }

    [Fact]
    public void PreservesNamespace()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.SimpleClickableClass, options);

        // Assert
        Assert.Contains("namespace Brinell.Maui.Controls", generatedCode);
    }

    [Fact]
    public void GeneratesMultipleMethods()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.MultiMethodClass, options);

        // Assert
        Assert.Contains("public TScope Click", generatedCode);
        Assert.Contains("public TScope Hover", generatedCode);
    }

    [Fact]
    public void HandlesEmptyMethodList()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true
        };

        // Act
        var generatedCode = generator.Generate(SampleCodeFixtures.NoMethodsClass, options);

        // Assert
        Assert.NotEmpty(generatedCode);
        Assert.Contains("namespace Brinell.Maui.Controls", generatedCode);
        // No wrapper methods should be generated
        Assert.DoesNotContain("public TScope", generatedCode);
    }

    [Fact]
    public void ThrowsWhenClassNotFound()
    {
        // Arrange
        var generator = new MethodWrapperGenerator();
        var options = new GeneratorOptions
        {
            Handlers = new List<IMethodHandler> { new CoreMethodHandler() },
            IncludeGeneratedHeader = true,
            TargetClassName = "NonExistentClass"
        };

        // Act & Assert
        var ex = Assert.Throws<InvalidOperationException>(() =>
            generator.Generate(SampleCodeFixtures.SimpleClickableClass, options));
        
        Assert.Contains("NonExistentClass", ex.Message);
    }
}

