// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Graphics;


/// <summary>
/// MAUI GraphicsView control for 2D graphics rendering (new in MAUI 8+).
/// GraphicsView provides a canvas for custom drawing and graphics operations.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class GraphicsView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
