<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.Maui</RootNamespace>
    <Description>MAUI UI testing automation using Appium. Provides controls and page objects for cross-platform MAUI application testing.</Description>
    <PackageId>Brinell.Maui</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brinell.Core\Brinell.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Appium.WebDriver" />
  </ItemGroup>

</Project>
