using System.Text;

namespace Brinell.Samples.Todo.JourneyCoverage;

/// <summary>One assignment from <c>journeys.md</c> - a subtask in a tier - and what covers it.</summary>
/// <param name="Subtask">The subtask.</param>
/// <param name="Tier">The tier it is assigned to.</param>
/// <param name="CoveredBy">The tests (or, for <see cref="Tier.Manual"/>, the charter) that cover it.</param>
public sealed record Assignment(Subtask Subtask, Tier Tier, IReadOnlyList<string> CoveredBy)
{
    /// <summary>Whether anything covers it.</summary>
    public bool IsCovered => CoveredBy.Count > 0;
}

/// <summary>
/// <c>journeys.md</c> compared with the tests' traits and the manual charters.
/// </summary>
public sealed class CoverageReport
{
    private CoverageReport(IReadOnlyList<Subtask> subtasks, IReadOnlyList<TestMethod> tests, IReadOnlyList<Assignment> assignments)
    {
        Subtasks = subtasks;
        Tests = tests;
        Assignments = assignments;
    }

    /// <summary>The subtasks of <c>journeys.md</c>.</summary>
    public IReadOnlyList<Subtask> Subtasks { get; }

    /// <summary>The tests of the sample's test assemblies.</summary>
    public IReadOnlyList<TestMethod> Tests { get; }

    /// <summary>Every subtask-in-a-tier, with what covers it.</summary>
    public IReadOnlyList<Assignment> Assignments { get; }

    /// <summary>Builds the report.</summary>
    /// <param name="journeysMarkdown">The text of <c>journeys.md</c>.</param>
    /// <param name="chartersMarkdown">The text of <c>manual/charters.md</c>.</param>
    /// <param name="tests">The tests.</param>
    public static CoverageReport Build(string journeysMarkdown, string chartersMarkdown, IReadOnlyList<TestMethod> tests)
    {
        var subtasks = Journeys.Parse(journeysMarkdown);
        var assignments = subtasks
            .SelectMany(subtask => subtask.Tiers.Select(tier => new Assignment(subtask, tier, tier == Tier.Manual
                ? (chartersMarkdown.Contains(subtask.Id, StringComparison.Ordinal) ? ["manual/charters.md"] : [])
                : [.. tests.Where(t => t.Journeys.Contains(subtask.Id) && t.Covers(tier)).Select(t => t.Name)])))
            .ToList();

        return new CoverageReport(subtasks, tests, assignments);
    }

    /// <summary>The number of test cases (theory rows counted) in a pyramid tier.</summary>
    public int CasesIn(string pyramid) => Tests.Where(t => t.Pyramid == pyramid).Sum(t => t.Cases);

    /// <summary>The report as Markdown: the per-tier counts, then one row per subtask.</summary>
    public string ToMarkdown()
    {
        var text = new StringBuilder();
        text.AppendLine("# Todo journey coverage");
        text.AppendLine();
        text.AppendLine("Generated by `Brinell.Samples.Todo.JourneyCoverage` from `journeys.md` and the tests' traits.");
        text.AppendLine();
        text.AppendLine("## Test counts per tier");
        text.AppendLine();
        text.AppendLine("| Pyramid | Tests | Cases |");
        text.AppendLine("| --- | ---: | ---: |");
        foreach (var pyramid in new[] { "Unit", "Integration", "Contract", "UiHermetic", "UiLive" })
        {
            text.AppendLine($"| {pyramid} | {Tests.Count(t => t.Pyramid == pyramid)} | {CasesIn(pyramid)} |");
        }

        text.AppendLine();
        text.AppendLine("## Subtasks");
        text.AppendLine();
        text.AppendLine("| Id | Subtask | Tier | Covered by |");
        text.AppendLine("| --- | --- | --- | --- |");
        foreach (var assignment in Assignments)
        {
            var coveredBy = assignment.IsCovered ? string.Join("<br>", assignment.CoveredBy) : "**MISSING**";
            text.AppendLine($"| {assignment.Subtask.Id} | {assignment.Subtask.Text} | {assignment.Tier} | {coveredBy} |");
        }

        return text.ToString();
    }
}
