using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI CarouselView: a swipeable collection with a notion of current position.
/// </summary>
/// <remarks>
/// <para>
/// Derive from this rather than instantiating it — the base is self-referencing so that
/// every member returns the concrete collection type:
/// </para>
/// <code>
/// public class BannerCarousel : CarouselView&lt;HomePage, BannerCarousel, BannerCard&gt;
/// {
///     public BannerCarousel(IMauiScope&lt;HomePage&gt; scope)
///         : base(scope, "Banners", ItemStrategy.ByAutomationId("BannerCard"),
///                (c, root, i) =&gt; new BannerCard(c, root, i)) { }
/// }
/// </code>
/// <para>
/// Position lives here rather than on <see cref="CollectionObjectBase{TParent, TSelf, TItem}"/>:
/// only a carousel has a "current" item, so putting it on the shared base would give every
/// collection a member most cannot honour.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The carousel type itself (self-referencing).</typeparam>
/// <typeparam name="TItem">The card type.</typeparam>

public abstract partial class CarouselView<TParent, TSelf, TItem> : CollectionObjectBase<TParent, TSelf, TItem>
    where TParent : IMauiScope<TParent>
    where TSelf : CarouselView<TParent, TSelf, TItem>
    where TItem : class, IMauiItemContainer<TSelf, TItem>
{
    #region Position (GetPosition / WaitPosition / AssertPosition)

    public int? GetPosition(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPositionCore(element), timeoutMs);
    }

    public bool? WaitPosition(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPositionCore(element) == expected,
           timeoutMs);
    }

    public TSelf AssertPosition(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPositionCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Position to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region LoopEnabled (IsLoopEnabled / WaitLoopEnabled / AssertLoopEnabled)

    public bool? IsLoopEnabled()
    {
        return IsLoopEnabledCore(TryFindElement()) == true;
    }

    public bool WaitLoopEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsLoopEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertLoopEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsLoopEnabledCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected LoopEnabled to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region SwipeNext

    public TSelf SwipeNext()
    {
        return RunDoWithElement(element => { SwipeNextCore(element); });
    }

    #endregion
    #region SwipePrevious

    public TSelf SwipePrevious()
    {
        return RunDoWithElement(element => { SwipePreviousCore(element); });
    }

    #endregion

}
