using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI CarouselView: a swipeable collection with a notion of current position.
/// </summary>
/// <remarks>
/// <para>
/// Derive from this rather than instantiating it — the base is self-referencing so that
/// every member returns the concrete collection type:
/// </para>
/// <code>
/// public class BannerCarousel : CarouselView&lt;HomePage, BannerCarousel, BannerCard&gt;
/// {
///     public BannerCarousel(IMauiScope&lt;HomePage&gt; scope)
///         : base(scope, "Banners", ItemStrategy.ByAutomationId("BannerCard"),
///                (c, root, i) =&gt; new BannerCard(c, root, i)) { }
/// }
/// </code>
/// <para>
/// There is deliberately no <c>Position</c> or <c>IsLoopEnabled</c> here. Both were read from
/// a MAUI bindable property through <c>GetAttribute</c>, and neither platform publishes those
/// to automation: Windows maps seven attribute names and nothing else, Android raises for an
/// unknown one. The members existed and answered a constant - 0 and false - whatever the app
/// did. A carousel's position needs an automation source before it can be reported.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The carousel type itself (self-referencing).</typeparam>
/// <typeparam name="TItem">The card type.</typeparam>

public abstract partial class CarouselView<TParent, TSelf, TItem> : CollectionObjectBase<TParent, TSelf, TItem>
    where TParent : IMauiScope<TParent>
    where TSelf : CarouselView<TParent, TSelf, TItem>
    where TItem : class, IMauiItemContainer<TSelf, TItem>
{
    #region SwipeNext

    public TSelf SwipeNext()
    {
        return RunDoWithElement(element => { SwipeNextCore(element); });
    }

    #endregion
    #region SwipePrevious

    public TSelf SwipePrevious()
    {
        return RunDoWithElement(element => { SwipePreviousCore(element); });
    }

    #endregion

}
