using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI CollectionView: a scrollable collection that hands out typed, scoped rows.
/// </summary>
/// <remarks>
/// <para>
/// Derive from this rather than instantiating it — <see cref="CollectionObjectBase{TParent, TSelf, TItem}"/>
/// is self-referencing so that every member returns the concrete collection type and a
/// chain stays inside it:
/// </para>
/// <code>
/// public class ProductCollection : CollectionView&lt;ProductsPage, ProductCollection, ProductRow&gt;
/// {
///     public ProductCollection(IMauiScope&lt;ProductsPage&gt; scope)
///         : base(scope, "ProductList", ItemStrategy.ByAutomationId("ProductRow"),
///                (c, root, i) =&gt; new ProductRow(c, root, i)) { }
/// }
/// </code>
/// <para>
/// This replaces the former <c>CollectionView&lt;TScope, TItem&gt; : List&lt;&gt;</c>, which
/// looked rows up page-wide by an indexed AutomationId. Rows are now found within the
/// collection and scoped to their own root, so an item template can repeat the same ids on
/// every row — the normal MAUI authoring style.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type (a page or another container).</typeparam>
/// <typeparam name="TSelf">The collection type itself (self-referencing).</typeparam>
/// <typeparam name="TItem">The row type.</typeparam>

public abstract partial class CollectionView<TParent, TSelf, TItem> : CollectionObjectBase<TParent, TSelf, TItem>
    where TParent : IMauiScope<TParent>
    where TSelf : CollectionView<TParent, TSelf, TItem>
    where TItem : class, IMauiItemContainer<TSelf, TItem>
{

}
