using System.Globalization;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI IndicatorView control for displaying carousel or collection indicators.
/// IndicatorView shows visual indicators (typically dots) representing positions in a collection.
/// </summary>
/// <remarks>
/// <para>
/// <b>Not in the Windows automation tree at all</b> (probed 2026-09-18, MAUI 10): the dots are
/// drawn with no automation element, and the view itself publishes none either. This control
/// resolves it through the app's bridge declaration instead
/// (<see cref="IMauiElement.TryFindDeclared"/>); the app must declare
/// <c>uia:GestureAutomation.Verbs="GetState"</c> on it. The bridge answers <c>Position</c> (the
/// selected dot), <c>Count</c> (the number of dots), <c>IsVisible</c> and <c>IsEnabled</c>.
/// </para>
/// <para>
/// <b>Android.</b> Where the view is in the tree it is found there; no state read answers
/// <c>Position</c> or <c>Count</c>, so they are null.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class IndicatorView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Position (GetPosition / WaitPosition / AssertPosition)

    public int? GetPosition(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPositionCore(element), timeoutMs);
    }

    public bool WaitPosition(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPositionCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertPosition(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPositionCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Position to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Count (GetCount / WaitCount / AssertCount)

    public int? GetCount(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetCountCore(element), timeoutMs);
    }

    public bool WaitCount(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetCountCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertCount(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetCountCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Count to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
