// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI IndicatorView control for displaying carousel or collection indicators.
/// IndicatorView shows visual indicators (typically dots) representing positions in a collection.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class IndicatorView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
