// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI TableView control for displaying grouped settings and form-style content.
/// TableView uses sections (TableSection) with cells (TextCell, SwitchCell, EntryCell, etc.).
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TableView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Intent (GetIntent / WaitIntent / AssertIntent)

    public string? GetIntent(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetIntentCore(element), timeoutMs);
    }

    public bool? WaitIntent(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetIntentCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertIntent(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetIntentCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Intent to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
