// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Collection;


/// <summary>
/// MAUI TableView control for displaying grouped settings and form-style content.
/// TableView uses sections (TableSection) with cells (TextCell, SwitchCell, EntryCell, etc.).
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TableView<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
