// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Samples.Todo.UITests.Controls;


/// <summary>
/// A label the app hides when it has nothing to say - a row's due date - for which "not shown" is
/// an answer rather than a failure.
/// </summary>
/// <remarks>
/// A hidden MAUI view leaves the automation tree on both platforms, so <c>IsShown</c> is false for a
/// missing label. Plain <c>IsVisible</c> reads null for a missing element instead of false.
/// </remarks>
/// <typeparam name="TScope">The containing scope type, normally a row.</typeparam>

public partial class ShownLabel<TScope> : Label<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Shown (IsShown / WaitShown / AssertShown)

    public bool? IsShown()
    {
        return IsShownCore(TryFindElement()) == true;
    }

    public bool WaitShown(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsShownCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertShown(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsShownCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Shown to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
