// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Samples.Todo.UITests.Controls;


/// <summary>
/// A list row's "not synced yet" marker (●).
/// </summary>
/// <remarks>
/// The app hides the marker once the row is synced, and a hidden MAUI view leaves the Windows
/// automation tree altogether (probed 2026-09-18: <c>TodoRow_Pending</c> is present with the name
/// "Not synced yet" before Sync and absent after). So absence is the answer "synced":
/// <c>IsShown</c> is false for a missing marker, where plain <c>IsVisible</c> would read null.
/// </remarks>
/// <typeparam name="TScope">The containing scope type, normally the row.</typeparam>

public partial class TodoPendingMark<TScope> : Label<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Shown (IsShown / WaitShown / AssertShown)

    public bool? IsShown()
    {
        return IsShownCore(TryFindElement()) == true;
    }

    public bool WaitShown(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsShownCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertShown(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsShownCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Shown to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
