// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Samples.Todo.UITests.Controls;


/// <summary>
/// The Todo app's status control (<c>TodoStatusView</c>): a glyph, the status name, and a Next
/// button that cycles Open, In progress, Done.
/// </summary>
/// <remarks>
/// <para>
/// <b>A component.</b> The app gives the control its AutomationId; the control fixes its parts'
/// ids itself (<c>StatusGlyph</c>, <c>StatusText</c>, <c>StatusNext</c>). Those ids repeat in every
/// list row, so they are only unique inside the component's root, which is what the component
/// scopes to.
/// </para>
/// <para>
/// <b>Route, Windows:</b> the root is a group (the app registers the Brinell automation handlers,
/// without which a <c>ContentView</c> publishes no AutomationId), the glyph and name are text, and
/// Next answers <c>InvokePattern</c>. No bridge (AD-008, test 1). Probed 2026-09-18: the list row
/// root reads <c>Status: Overdue</c> with the two text parts and no button; the detail page's has
/// all three.
/// </para>
/// <para>
/// <b>Overdue is what the user sees,</b> not a status: a todo past its due date shows Overdue until
/// it is Done. Cycling a past-due todo therefore reads Overdue, Overdue, Done.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class TodoStatus<TScope> : ComponentObjectBase<TScope, TodoStatus<TScope>>
    where TScope : IMauiScope<TScope>
{
    #region GetStatus (shortcut to Text.GetText)

    public string? GetStatus(int? timeoutMs = null)
       => Text.GetText(timeoutMs);

    public bool WaitStatus(string? expected, int? timeoutMs = null)
       => Text.WaitText(expected, timeoutMs);

    public TodoStatus<TScope> AssertStatus(string? expected, string? message = null, int? timeoutMs = null)
       => Text.AssertText(expected, message, timeoutMs);

    #endregion
    #region GetGlyph (shortcut to Glyph.GetText)

    public string? GetGlyph(int? timeoutMs = null)
       => Glyph.GetText(timeoutMs);

    public bool WaitGlyph(string? expected, int? timeoutMs = null)
       => Glyph.WaitText(expected, timeoutMs);

    public TodoStatus<TScope> AssertGlyph(string? expected, string? message = null, int? timeoutMs = null)
       => Glyph.AssertText(expected, message, timeoutMs);

    #endregion
    #region IsChangeable (shortcut to Next.IsShown)

    public bool? IsChangeable()
       => Next.IsShown();

    public bool WaitChangeable(bool? expected = true, int? timeoutMs = null)
       => Next.WaitShown(expected, timeoutMs);

    public TodoStatus<TScope> AssertChangeable(bool? expected = true, string? message = null, int? timeoutMs = null)
       => Next.AssertShown(expected, message, timeoutMs);

    #endregion

}
