// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Samples.Todo.UITests.Controls;


/// <summary>
/// The Next button of a <see cref="TodoStatus{TScope}"/>.
/// </summary>
/// <remarks>
/// A read-only status control (every list row) has no Next button at all, and that is an answer,
/// not a failure: <c>IsShown</c> is false for a missing button. Plain <c>IsVisible</c> reads null
/// for a missing element, and <c>IsExists</c> may scroll the list and find another row's button.
/// </remarks>
/// <typeparam name="TScope">The containing scope type, normally the status control.</typeparam>

public partial class TodoStatusNextButton<TScope> : Button<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Shown (IsShown / WaitShown / AssertShown)

    public bool? IsShown()
    {
        return IsShownCore(TryFindElement()) == true;
    }

    public bool WaitShown(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsShownCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertShown(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsShownCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Shown to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
