// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// CommunityToolkit.Maui <c>AvatarView</c>: initials or an image in a bordered shape.
/// </summary>
/// <remarks>
/// Read from the automation tree alone, no bridge: on Windows the avatar is a group whose child
/// is a text element carrying the initials, or an image element when an image source is set.
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class AvatarView<TScope> : Brinell.Maui.Controls.Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Text (GetText / WaitText / AssertText)

    public string? GetText(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTextCore(element), timeoutMs);
    }

    public bool WaitText(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTextCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertText(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTextCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Text to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitTextEmpty(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => string.IsNullOrEmpty(GetTextCore(element)) == expected,
           timeoutMs);
    }

    public TScope AssertTextEmpty(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => (bool?)string.IsNullOrEmpty(GetTextCore(element)), (actual, expected1) => (actual == expected1),
           message ?? $"Expected TextEmpty to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region ShowingImage (IsShowingImage / WaitShowingImage / AssertShowingImage)

    public bool? IsShowingImage()
    {
        return IsShowingImageCore(TryFindElement()) == true;
    }

    public bool WaitShowingImage(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsShowingImageCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertShowingImage(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsShowingImageCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected ShowingImage to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
