using Brinell.Maui.Controls.Display;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// The initials an <see cref="AvatarView{TScope}"/> shows when it has no image.
/// </summary>
/// <remarks>
/// On Windows this is the avatar's text child. When an image source is set the image replaces it,
/// so "no initials" is an answer here, not a failure: <c>GetInitials</c> reads once and returns
/// null rather than waiting for text that will not come.
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class AvatarInitials<TScope> : Label<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Initials (GetInitials / WaitInitials / AssertInitials)

    public string? GetInitials(int? timeoutMs = null)
    {
        return RunGetWithOptionalElement(element => GetInitialsCore(element), timeoutMs);
    }

    public bool WaitInitials(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => GetInitialsCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertInitials(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           element => GetInitialsCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Initials to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitInitialsEmpty(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => string.IsNullOrEmpty(GetInitialsCore(element)) == expected,
           timeoutMs);
    }

    public TScope AssertInitialsEmpty(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           element => (bool?)string.IsNullOrEmpty(GetInitialsCore(element)), (actual, expected1) => (actual == expected1),
           message ?? $"Expected InitialsEmpty to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
