using Brinell.Maui.Controls.Display;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// The image an <see cref="AvatarView{TScope}"/> shows when an image source is set.
/// </summary>
/// <remarks>
/// Without an image source the avatar has no image element at all, and that is an answer, not a
/// failure: <c>IsShown</c> is false for a missing image. Plain <c>IsVisible</c> reads null for a
/// missing element, so <c>AssertVisible(false)</c> would never pass here.
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class AvatarImage<TScope> : Image<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Shown (IsShown / WaitShown / AssertShown)

    public bool? IsShown()
    {
        return IsShownCore(TryFindElement()) == true;
    }

    public bool WaitShown(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsShownCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertShown(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsShownCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Shown to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
