using Brinell.Maui.Containers;
using Brinell.Maui.Controls.Display;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// CommunityToolkit.Maui <c>AvatarView</c>: initials or an image in a bordered shape.
/// </summary>
/// <remarks>
/// <para>
/// Read from the automation tree alone, no bridge: on Windows the avatar is a group whose child
/// is a text element carrying the initials, or an image element when an image source is set.
/// </para>
/// <para>
/// The parts own the reads; this component forwards to them through shortcuts, so each call is
/// the part's own single unit of work.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class AvatarView<TScope> : ComponentObjectBase<TScope, AvatarView<TScope>>
    where TScope : IMauiScope<TScope>
{
    #region GetInitials (shortcut to Initials.GetInitials)

    public string? GetInitials(int? timeoutMs = null)
       => Initials.GetInitials(timeoutMs);

    public bool WaitInitials(string? expected, int? timeoutMs = null)
       => Initials.WaitInitials(expected, timeoutMs);

    public AvatarView<TScope> AssertInitials(string? expected, string? message = null, int? timeoutMs = null)
       => Initials.AssertInitials(expected, message, timeoutMs);

    public bool WaitInitialsEmpty(bool? expected = true, int? timeoutMs = null)
       => Initials.WaitInitialsEmpty(expected, timeoutMs);

    public AvatarView<TScope> AssertInitialsEmpty(bool? expected = true, string? message = null, int? timeoutMs = null)
       => Initials.AssertInitialsEmpty(expected, message, timeoutMs);

    #endregion
    #region IsShowingImage (shortcut to Image.IsShown)

    public bool? IsShowingImage()
       => Image.IsShown();

    public bool WaitShowingImage(bool? expected = true, int? timeoutMs = null)
       => Image.WaitShown(expected, timeoutMs);

    public AvatarView<TScope> AssertShowingImage(bool? expected = true, string? message = null, int? timeoutMs = null)
       => Image.AssertShown(expected, message, timeoutMs);

    #endregion

}
