// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// CommunityToolkit.Maui <c>DrawingView</c>: a surface the user draws lines on.
/// </summary>
/// <remarks>
/// <para>
/// <b>Not in the Windows automation tree by id.</b> The view renders as an unnamed image, so this
/// control resolves it through the app's bridge declaration instead
/// (<see cref="IMauiElement.TryFindDeclared"/>). That element answers state reads and gestures
/// only, which is all this control asks of it.
/// </para>
/// <para>
/// <b>A stroke on Windows is arranged, not drawn.</b> The app declares <c>Pan,GetState</c> and a
/// sink adds one straight line through the view's own completion entry point, so the page sees a
/// finished line. A test of real drawing belongs on Android, where the pan is touch input.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class DrawingView<TScope> : Brinell.Maui.Controls.Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region LineCount (GetLineCount / WaitLineCount / AssertLineCount)

    public int? GetLineCount(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetLineCountCore(element), timeoutMs);
    }

    public bool WaitLineCount(int? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetLineCountCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertLineCount(int? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetLineCountCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected LineCount to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region DrawLine

    public TScope DrawLine(int deltaX, int deltaY, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { DrawLineCore(element, deltaX, deltaY, timeoutMs); }, timeoutMs);
    }

    #endregion

}
