using Brinell.Core.Utilities;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// CommunityToolkit.Maui <c>Expander</c>: a header that shows or hides its content when tapped.
/// </summary>
/// <remarks>
/// <para>
/// <b>Windows needs the app's sink.</b> The expander publishes no ExpandCollapse or Invoke
/// pattern, and its header tap is a toolkit-internal <c>Tapped</c> handler the bridge cannot
/// bind. The app declares <c>Tap,GetState</c> on the expander and attaches a sink that toggles
/// <c>IsExpanded</c> and answers <c>GetState("IsExpanded")</c>; see <c>ToolkitVerbSink</c> in the
/// sample app and <c>.my/communitytoolkit/probe.md</c>.
/// </para>
/// <para>
/// Android and iOS tap the element with touch input. They have no state read, so
/// <c>IsExpanded</c> answers null there.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Expander<TScope> : Brinell.Maui.Controls.Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Expanded (IsExpanded / WaitExpanded / AssertExpanded)

    public bool? IsExpanded()
    {
        return IsExpandedCore(TryFindElement()) == true;
    }

    public bool WaitExpanded(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsExpandedCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertExpanded(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsExpandedCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Expanded to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Toggle

    public TScope Toggle(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ToggleCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Expand

    public TScope Expand(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ExpandCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Collapse

    public TScope Collapse(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { CollapseCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetExpanded

    public TScope SetExpanded(bool? expanded, int? timeoutMs = null)
    {
        return RunSetWithElement(expanded, element => { SetExpandedCore(element, expanded, timeoutMs); }, timeoutMs);
    }

    #endregion

}
