using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// CommunityToolkit.Maui <c>Popup</c>: a view shown modally over the page, scoped as a container.
/// </summary>
/// <remarks>
/// <para>
/// <b>Found from the app, not the page.</b> The toolkit shows a popup as a modal page, so its
/// root is not inside the page that raised it. On Windows it is still in the main window's tree,
/// with its own AutomationId, and its buttons answer Invoke - no bridge is involved.
/// </para>
/// <para>
/// <b>Not cached.</b> A popup opens and closes during a test, so every lookup finds it again.
/// </para>
/// <para>
/// Subclass it for a popup with known content, as with <c>ContentView</c>, or use
/// <see cref="Popup{TParent}"/> with <c>Label(id)</c> and <c>Button(id)</c>.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The scope that raises the popup, usually the page.</typeparam>
/// <typeparam name="TSelf">The popup type itself (self-referencing for fluent returns).</typeparam>

public partial class Popup<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : Popup<TParent, TSelf>
{
    #region Open (IsOpen / WaitOpen / AssertOpen)

    public bool? IsOpen()
    {
        return IsOpenCore(TryFindElement()) == true;
    }

    public bool WaitOpen(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsOpenCore(element) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertOpen(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           IsOpenCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Open to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
