using Brinell.Core.Utilities;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Views;


/// <summary>
/// CommunityToolkit.Maui <c>RatingView</c>: a row of shapes the user taps to give a rating.
/// </summary>
/// <remarks>
/// <para>
/// <b>A range control whose steps are stars.</b> Value is the rating, Maximum is
/// <c>MaximumRating</c>, Minimum is 0 and Step is 1. Setting a value taps the star with that
/// number, as a user would; a rating of 0 has no star to tap and is refused.
/// </para>
/// <para>
/// <b>Windows needs the app's sink.</b> The view publishes no RangeValue pattern and its stars
/// have neither ids nor patterns. The app declares <c>SelectIndex,GetState</c> on it and attaches
/// a sink that taps star <c>i</c> and answers <c>Rating</c>, <c>MaximumRating</c> and
/// <c>IsReadOnly</c>; see <c>ToolkitVerbSink</c> in the sample app.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class RatingView<TScope> : Brinell.Maui.Controls.Base.RangeControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region ReadOnly (IsReadOnly / WaitReadOnly / AssertReadOnly)

    public bool? IsReadOnly()
    {
        return IsReadOnlyCore(TryFindElement()) == true;
    }

    public bool WaitReadOnly(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsReadOnlyCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertReadOnly(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsReadOnlyCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected ReadOnly to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region TapStar

    public TScope TapStar(int? star, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { TapStarCore(element, star, timeoutMs); }, timeoutMs);
    }

    #endregion

}
