// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Range;


/// <summary>
/// MAUI Slider control for continuous value selection.
/// Inherits GetValue, SetValue, GetMinimum, GetMaximum, Increment, Decrement from RangeControlBase.
/// Provides additional slider-specific methods like SlideToPercentage.
/// Overrides SetValueCore to use keyboard-based approach since Windows Appium driver 
/// doesn't support mouse Actions API (only pen/touch pointer input supported).
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Slider<TScope> : Base.RangeControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Percentage (GetPercentage / WaitPercentage / AssertPercentage)

    public double? GetPercentage(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetPercentageCore(element), timeoutMs);
    }

    public bool? WaitPercentage(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetPercentageCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertPercentage(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetPercentageCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Percentage to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
