using Brinell.Core.Locators;
using System.Globalization;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Range;


/// <summary>
/// MAUI Stepper control with +/- buttons for discrete value changes.
/// Inherits GetValue, SetValue, GetMinimum, GetMaximum, Increment, Decrement from RangeControlBase.
/// Provides additional stepper-specific methods like IncrementBy and DecrementBy.
/// Overrides Increment/Decrement to invoke the stepper's own buttons instead of sending keys.
///
/// Windows MAUI Note: On Windows, MAUI Stepper doesn't expose a single element with the AutomationId.
/// Instead, it exposes separate button elements with "{AutomationId}Minus" and "{AutomationId}Plus".
/// This control resolves through that pair, presses them through the Invoke pattern, and reads
/// Value, Minimum, Maximum and Increment from the app with the bridge's GetState verb, which the
/// Stepper must declare.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Stepper<TScope> : Base.RangeControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region IncrementBy

    public TScope IncrementBy(int? times, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { IncrementByCore(element, times, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region DecrementBy

    public TScope DecrementBy(int? times, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { DecrementByCore(element, times, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetToMinimum

    public TScope SetToMinimum(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SetToMinimumCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetToMaximum

    public TScope SetToMaximum(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SetToMaximumCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion

}
