// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Selection;


/// <summary>
/// MAUI Picker control for dropdown selection.
/// Inherits SelectByText, SelectByIndex, GetSelectedText from SelectorControlBase.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Picker<TScope> : Base.SelectorControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Title (GetTitle / WaitTitle / AssertTitle)

    public string? GetTitle(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetTitleCore(element), timeoutMs);
    }

    public bool? WaitTitle(string? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetTitleCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertTitle(string? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetTitleCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Title to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
