<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.Stride.UITests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\srcnew\Brinell.Core\Brinell.Core.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Stride\Brinell.Stride.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Automation\Brinell.Automation.csproj" />
  </ItemGroup>

</Project>
