using Brinell.Maui.Containers;
using Brinell.Maui.Controls.Buttons;
using Brinell.Maui.Controls.Range;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Media;


/// <summary>
/// CommunityToolkit.Maui <c>MediaElement</c>: audio and video playback with platform transport
/// controls.
/// </summary>
/// <remarks>
/// <para>
/// <b>Driven and read through its transport controls, not through the element.</b> On Windows the
/// media element is not in the tree by its AutomationId, but the WinUI transport controls are,
/// flattened into the page: <c>PlayPauseButton</c> answers Invoke, the seek slider publishes
/// RangeValue, and the elapsed and remaining times are text. Everything here goes through those,
/// with no bridge.
/// </para>
/// <para>
/// <b>The parts own the behaviour.</b> <see cref="MediaPlayPauseButton{TScope}"/> knows whether
/// media plays and how to change it; <see cref="MediaTimeLabel{TScope}"/> reads a time. This
/// component forwards to them through shortcuts, so each call is the part's own single unit of
/// work. Only members that need two parts are hand-written here.
/// </para>
/// <para>
/// <b>Not the toolkit's <c>CurrentState</c>.</b> Measured on toolkit 10.0.0 / Windows: after the
/// transport controls start playback, <c>CurrentState</c> stays <c>Opening</c> and
/// <c>StateChanged</c> never fires, while the player plays. A state read from the app would be
/// wrong, so this control reads what the user sees. See <c>.my/communitytoolkit/probe.md</c>.
/// </para>
/// <para>
/// <b>Limits.</b> One media element per scope on Windows: the transport ids are fixed, so put each
/// media element in its own container. Playback controls must be shown
/// (<c>ShouldShowPlaybackControls</c>). <c>IsPlaying</c> reads the play/pause button's name, which
/// Windows localizes; it matches the English "Pause". The transport has no stop button, so
/// <see cref="Stop"/> pauses and seeks to the start. Android publishes none of these ids yet.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class MediaElement<TScope> : ComponentObjectBase<TScope, MediaElement<TScope>>
    where TScope : IMauiScope<TScope>
{
    #region IsPlaying (shortcut to PlayPauseButton.IsPlaying)

    public bool? IsPlaying()
       => PlayPauseButton.IsPlaying();

    public bool WaitPlaying(bool? expected = true, int? timeoutMs = null)
       => PlayPauseButton.WaitPlaying(expected, timeoutMs);

    public MediaElement<TScope> AssertPlaying(bool? expected = true, string? message = null, int? timeoutMs = null)
       => PlayPauseButton.AssertPlaying(expected, message, timeoutMs);

    #endregion
    #region Pause (shortcut to PlayPauseButton.Pause)

    public MediaElement<TScope> Pause(int? timeoutMs = null)
       => PlayPauseButton.Pause(timeoutMs);

    #endregion
    #region GetProgress (shortcut to ProgressSlider.GetValue)

    public double? GetProgress(int? timeoutMs = null)
       => ProgressSlider.GetValue(timeoutMs);

    public bool WaitProgress(double? expected, int? timeoutMs = null)
       => ProgressSlider.WaitValue(expected, timeoutMs);

    public MediaElement<TScope> AssertProgress(double? expected, string? message = null, int? timeoutMs = null)
       => ProgressSlider.AssertValue(expected, message, timeoutMs);

    public bool WaitProgressGreaterThan(double? expected, int? timeoutMs = null)
       => ProgressSlider.WaitValueGreaterThan(expected, timeoutMs);

    public MediaElement<TScope> AssertProgressGreaterThan(double? expected, string? message = null, int? timeoutMs = null)
       => ProgressSlider.AssertValueGreaterThan(expected, message, timeoutMs);

    public bool WaitProgressAtLeast(double? expected, int? timeoutMs = null)
       => ProgressSlider.WaitValueAtLeast(expected, timeoutMs);

    public MediaElement<TScope> AssertProgressAtLeast(double? expected, string? message = null, int? timeoutMs = null)
       => ProgressSlider.AssertValueAtLeast(expected, message, timeoutMs);

    #endregion
    #region GetElapsed (shortcut to TimeElapsedLabel.GetSeconds)

    public double? GetElapsed(int? timeoutMs = null)
       => TimeElapsedLabel.GetSeconds(timeoutMs);

    public bool WaitElapsed(double? expected, int? timeoutMs = null)
       => TimeElapsedLabel.WaitSeconds(expected, timeoutMs);

    public MediaElement<TScope> AssertElapsed(double? expected, string? message = null, int? timeoutMs = null)
       => TimeElapsedLabel.AssertSeconds(expected, message, timeoutMs);

    public bool WaitElapsedGreaterThan(double? expected, int? timeoutMs = null)
       => TimeElapsedLabel.WaitSecondsGreaterThan(expected, timeoutMs);

    public MediaElement<TScope> AssertElapsedGreaterThan(double? expected, string? message = null, int? timeoutMs = null)
       => TimeElapsedLabel.AssertSecondsGreaterThan(expected, message, timeoutMs);

    public bool WaitElapsedAtLeast(double? expected, int? timeoutMs = null)
       => TimeElapsedLabel.WaitSecondsAtLeast(expected, timeoutMs);

    public MediaElement<TScope> AssertElapsedAtLeast(double? expected, string? message = null, int? timeoutMs = null)
       => TimeElapsedLabel.AssertSecondsAtLeast(expected, message, timeoutMs);

    public bool WaitElapsedLessThan(double? expected, int? timeoutMs = null)
       => TimeElapsedLabel.WaitSecondsLessThan(expected, timeoutMs);

    public MediaElement<TScope> AssertElapsedLessThan(double? expected, string? message = null, int? timeoutMs = null)
       => TimeElapsedLabel.AssertSecondsLessThan(expected, message, timeoutMs);

    public bool WaitElapsedAtMost(double? expected, int? timeoutMs = null)
       => TimeElapsedLabel.WaitSecondsAtMost(expected, timeoutMs);

    public MediaElement<TScope> AssertElapsedAtMost(double? expected, string? message = null, int? timeoutMs = null)
       => TimeElapsedLabel.AssertSecondsAtMost(expected, message, timeoutMs);

    #endregion
    #region GetRemaining (shortcut to TimeRemainingLabel.GetSeconds)

    public double? GetRemaining(int? timeoutMs = null)
       => TimeRemainingLabel.GetSeconds(timeoutMs);

    public bool WaitRemaining(double? expected, int? timeoutMs = null)
       => TimeRemainingLabel.WaitSeconds(expected, timeoutMs);

    public MediaElement<TScope> AssertRemaining(double? expected, string? message = null, int? timeoutMs = null)
       => TimeRemainingLabel.AssertSeconds(expected, message, timeoutMs);

    public bool WaitRemainingGreaterThan(double? expected, int? timeoutMs = null)
       => TimeRemainingLabel.WaitSecondsGreaterThan(expected, timeoutMs);

    public MediaElement<TScope> AssertRemainingGreaterThan(double? expected, string? message = null, int? timeoutMs = null)
       => TimeRemainingLabel.AssertSecondsGreaterThan(expected, message, timeoutMs);

    public bool WaitRemainingAtLeast(double? expected, int? timeoutMs = null)
       => TimeRemainingLabel.WaitSecondsAtLeast(expected, timeoutMs);

    public MediaElement<TScope> AssertRemainingAtLeast(double? expected, string? message = null, int? timeoutMs = null)
       => TimeRemainingLabel.AssertSecondsAtLeast(expected, message, timeoutMs);

    public bool WaitRemainingLessThan(double? expected, int? timeoutMs = null)
       => TimeRemainingLabel.WaitSecondsLessThan(expected, timeoutMs);

    public MediaElement<TScope> AssertRemainingLessThan(double? expected, string? message = null, int? timeoutMs = null)
       => TimeRemainingLabel.AssertSecondsLessThan(expected, message, timeoutMs);

    public bool WaitRemainingAtMost(double? expected, int? timeoutMs = null)
       => TimeRemainingLabel.WaitSecondsAtMost(expected, timeoutMs);

    public MediaElement<TScope> AssertRemainingAtMost(double? expected, string? message = null, int? timeoutMs = null)
       => TimeRemainingLabel.AssertSecondsAtMost(expected, message, timeoutMs);

    #endregion

}
