using System.Text.RegularExpressions;
using Brinell.Core.Utilities;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Media;


/// <summary>
/// CommunityToolkit.Maui <c>MediaElement</c>: audio and video playback with platform transport
/// controls.
/// </summary>
/// <remarks>
/// <para>
/// <b>Driven and read through its transport controls, not through the element.</b> On Windows the
/// media element is not in the tree by its AutomationId, but the WinUI transport controls are,
/// flattened into the page: <c>PlayPauseButton</c> answers Invoke, the seek slider publishes
/// RangeValue, and the elapsed and remaining times are text. Everything here goes through those,
/// with no bridge.
/// </para>
/// <para>
/// <b>Not the toolkit's <c>CurrentState</c>.</b> Measured on toolkit 10.0.0 / Windows: after the
/// transport controls start playback, <c>CurrentState</c> stays <c>Opening</c> and
/// <c>StateChanged</c> never fires, while the player plays. A state read from the app would be
/// wrong, so this control reads what the user sees. See <c>.my/communitytoolkit/probe.md</c>.
/// </para>
/// <para>
/// <b>Limits.</b> One media element per scope on Windows: the transport ids are fixed, so put each
/// media element in its own container. Playback controls must be shown
/// (<c>ShouldShowPlaybackControls</c>). <c>IsPlaying</c> reads the play/pause button's name, which
/// Windows localizes; it matches the English "Pause". Android publishes none of these ids yet.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class MediaElement<TScope> : Brinell.Maui.Controls.Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Playing (IsPlaying / WaitPlaying / AssertPlaying)

    public bool? IsPlaying()
    {
        return IsPlayingCore(TryFindElement()) == true;
    }

    public bool WaitPlaying(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsPlayingCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertPlaying(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsPlayingCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Playing to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Progress (GetProgress / WaitProgress / AssertProgress)

    public double? GetProgress(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetProgressCore(element), timeoutMs);
    }

    public bool WaitProgress(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetProgressCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertProgress(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetProgressCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Progress to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Duration (GetDuration / WaitDuration / AssertDuration)

    public double? GetDuration(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetDurationCore(element), timeoutMs);
    }

    public bool WaitDuration(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetDurationCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertDuration(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetDurationCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Duration to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Play

    public TScope Play(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PlayCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Pause

    public TScope Pause(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PauseCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetPlaying

    public TScope SetPlaying(bool? playing, int? timeoutMs = null)
    {
        return RunSetWithElement(playing, element => { SetPlayingCore(element, playing, timeoutMs); }, timeoutMs);
    }

    #endregion

}
