using Brinell.Maui.Controls.Buttons;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Media;


/// <summary>
/// The media transport's play/pause button: one button whose name says what pressing it will do.
/// </summary>
/// <remarks>
/// <para>
/// <b>Windows</b>: the WinUI transport's <c>PlayPauseButton</c> answers Invoke and is named
/// "Play" while paused and "Pause" while playing. The name is localized; this matches English.
/// </para>
/// <para>
/// The button is enabled before the media has opened, and a press made then is dropped by the
/// player (probed 2026-09-18: enabled at 311 ms, media opened at 393 ms). This control cannot see
/// the media's state, so a component that owns this button waits for the media first; see
/// <see cref="MediaElement{TScope}"/>.
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class MediaPlayPauseButton<TScope> : Button<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Playing (IsPlaying / WaitPlaying / AssertPlaying)

    public bool? IsPlaying()
    {
        return IsPlayingCore(TryFindElement()) == true;
    }

    public bool WaitPlaying(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsPlayingCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertPlaying(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsPlayingCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Playing to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion
    #region Play

    public TScope Play(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PlayCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Pause

    public TScope Pause(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { PauseCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region SetPlaying

    public TScope SetPlaying(bool? playing, int? timeoutMs = null)
    {
        return RunSetWithElement(playing, element => { SetPlayingCore(element, playing, timeoutMs); }, timeoutMs);
    }

    #endregion

}
