using System.Text.RegularExpressions;
using Brinell.Maui.Controls.Display;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Media;


/// <summary>
/// One of the media transport's time readouts: elapsed or remaining playback time.
/// </summary>
/// <remarks>
/// <para>
/// <b>Windows</b>: the WinUI transport names its <c>TimeElapsedElement</c> and
/// <c>TimeRemainingElement</c> "Time elapsed 00:00:03" and "Time remaining 00:00:03". The name
/// carries the clock only while the media is open and not playing. Before the media opens, and
/// during playback, it is just "Time elapsed", and <c>GetSeconds</c> answers null; the clock is
/// then only in the Text pattern, which the driver does not read.
/// </para>
/// <para>
/// So <c>WaitSecondsAtLeast(0)</c> on the remaining time is "the media has opened" for a paused
/// player (probed 2026-09-18: no clock at 311 ms, "00:00:06" at 393 ms).
/// </para>
/// </remarks>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class MediaTimeLabel<TScope> : Label<TScope>
    where TScope : IMauiScope<TScope>
{
    #region Seconds (GetSeconds / WaitSeconds / AssertSeconds)

    public double? GetSeconds(int? timeoutMs = null)
    {
        return RunGetWithElement(element => GetSecondsCore(element), timeoutMs);
    }

    public bool WaitSeconds(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSecondsCore(element) == expected,
           timeoutMs);
    }

    public TScope AssertSeconds(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSecondsCore(element), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Seconds to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitSecondsGreaterThan(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSecondsCore(element) > expected,
           timeoutMs);
    }

    public TScope AssertSecondsGreaterThan(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSecondsCore(element), (actual, expected1) => (actual > expected1),
           message ?? $"Expected Seconds to be greater than '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitSecondsAtLeast(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSecondsCore(element) >= expected,
           timeoutMs);
    }

    public TScope AssertSecondsAtLeast(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSecondsCore(element), (actual, expected1) => (actual >= expected1),
           message ?? $"Expected Seconds to be at least '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitSecondsLessThan(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSecondsCore(element) < expected,
           timeoutMs);
    }

    public TScope AssertSecondsLessThan(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSecondsCore(element), (actual, expected1) => (actual < expected1),
           message ?? $"Expected Seconds to be less than '{expected}'. Locator: {Locator}", timeoutMs);
    }

    public bool WaitSecondsAtMost(double? expected, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => GetSecondsCore(element) <= expected,
           timeoutMs);
    }

    public TScope AssertSecondsAtMost(double? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           element => GetSecondsCore(element), (actual, expected1) => (actual <= expected1),
           message ?? $"Expected Seconds to be at most '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
