// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Shapes;


/// <summary>
/// MAUI Ellipse shape control for drawing elliptical or circular shapes.
/// Ellipse is used as a visual drawing element, typically not requiring interaction testing.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Ellipse<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
