// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls.Shapes;


/// <summary>
/// MAUI Path shape control for drawing complex vector paths.
/// Path is used as a visual drawing element, typically not requiring interaction testing.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class Path<TScope> : Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{

}
