using Brinell.Maui.Configuration;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Extensions.Controls.Selection;


/// <summary>
/// Shared GenericBrowser selector used by generated picker/drawer flows.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class GenericBrowser<TScope> : Brinell.Maui.Controls.Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SelectItem

    public TScope SelectItem(string identifier, string? visibleText = null, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SelectItemCore(element, identifier, visibleText, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region ToggleItem

    public TScope ToggleItem(string identifier, string? visibleText = null, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ToggleItemCore(element, identifier, visibleText, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Close

    public TScope Close(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { CloseCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion

}
