using Brinell.Maui.Configuration;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Extensions.Controls.Selection;


/// <summary>
/// List selection helper for MAUI list rows whose command surface may be exposed as
/// a UIA ListItem rather than the text/layout element found by AutomationId.
/// </summary>
/// <typeparam name="TScope">The containing scope type for fluent chaining.</typeparam>

public partial class SelectionList<TScope> : Brinell.Maui.Controls.Base.ViewBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SelectByAutomationId

    public TScope SelectByAutomationId(string automationId, int? timeoutMs = null)
    {
        return RunDoWithElement(element => { SelectByAutomationIdCore(element, automationId, timeoutMs); }, timeoutMs);
    }

    #endregion

}
