using Brinell.Maui.Containers;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.CommunityToolkit.Controls.Layouts;


/// <summary>
/// CommunityToolkit.Maui <c>StateContainer</c>: a layout that swaps its content for a state view
/// (loading, error, empty) while a state is set.
/// </summary>
/// <remarks>
/// <para>
/// <b>Read from the tree.</b> The layout keeps only the views for the current state as children,
/// so "which state is shown" is "which state view is present". No bridge: the tree already
/// answers, so a verb would fail AD-008's first test.
/// </para>
/// <para>
/// The state is named by the AutomationId of its view, because that is what a user-facing test can
/// see; the toolkit's state key is not published.
/// </para>
/// <para>
/// <b>Windows requires the automation handlers</b> for the host layout to publish its AutomationId,
/// as for any MAUI layout container.
/// </para>
/// </remarks>
/// <typeparam name="TParent">The parent scope type.</typeparam>
/// <typeparam name="TSelf">The container type itself (self-referencing for fluent returns).</typeparam>

public partial class StateContainer<TParent, TSelf> : ContainerObjectBase<TParent, TSelf>
    where TParent : IMauiScope<TParent>
    where TSelf : StateContainer<TParent, TSelf>
{
    #region Showing (IsShowing / WaitShowing / AssertShowing)

    public bool? IsShowing(string viewAutomationId)
    {
        return IsShowingCore(TryFindElement(), viewAutomationId) == true;
    }

    public bool WaitShowing(string viewAutomationId, bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithOptionalElement(expected,
           element => IsShowingCore(element, viewAutomationId) == expected!.Value,
           timeoutMs);
    }

    public TSelf AssertShowing(string viewAutomationId, bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithOptionalElement(expected,
           element => IsShowingCore(element, viewAutomationId), (actual, expected1) => (actual == expected1),
           message ?? $"Expected Showing to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
