using Brinell.Core.Abstractions.Controls;

// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

namespace Brinell.Maui.Controls;



public abstract partial class ControlBase<TScope>
    where TScope : IMauiScope<TScope>
{
    #region SendKeys

    public TScope SendKeys(string keys)
    {
        return RunDoWithElement(element => { SendKeysCore(element, keys); });
    }

    #endregion
    #region Visible (IsVisible / WaitVisible / AssertVisible)

    public bool? IsVisible()
    {
        return IsVisibleCore(TryFindElement()) == true;
    }

    public bool WaitVisible(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsVisibleCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertVisible(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsVisibleCore, (actual, expected1) => (actual == expected1),
           null, timeoutMs);
    }

    #endregion
    #region Enabled (IsEnabled / WaitEnabled / AssertEnabled)

    public bool? IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsEnabledCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertEnabled(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsEnabledCore, (actual, expected1) => (actual == expected1),
           null, timeoutMs);
    }

    #endregion
    #region Exists (IsExists / WaitExists / AssertExists)

    public bool IsExists()
    {
        return IsExistsCore(TryFindElement()) == true;
    }

    public bool WaitExists(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsExistsCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertExists(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsExistsCore, (actual, expected1) => (actual == expected1),
           null, timeoutMs);
    }

    #endregion

}
