using Brinell.Core.Abstractions.Controls;

namespace Brinell.Maui.Controls;

public partial class ControlBase<TScope>
{
    // Generated by CoreMethodHandler from SendKeysCore
    public TScope SendKeys(string keys, int? timeoutMs = null)
    {
        return RunSetWithElement(keys, element => { EnsureSettableCore(element); SendKeysCore(element, keys); }, timeoutMs);
    }

    // Generated by IsPropertyHandler
    public bool IsVisible()
    {
        return IsVisibleCore(TryFindElement()) == true;
    }

    public bool WaitVisible(bool? expected, int? timeoutMs = null)
    {
        if (expected == null) return true;
        return RunWaitWithElement(
            element => IsVisibleCore(element) == expected.Value,
            timeoutMs);
    }

    public TScope AssertVisible(bool? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
            IsVisibleCore, (actual, expected1) => (actual == expected1),
            null, timeoutMs);
    }

    public bool IsEnabled()
    {
        return IsEnabledCore(TryFindElement()) == true;
    }

    public bool WaitEnabled(bool? expected, int? timeoutMs = null)
    {
        if (expected == null) return true;
        return RunWaitWithElement(
            element => IsEnabledCore(element) == expected.Value,
            timeoutMs);
    }

    public TScope AssertEnabled(bool? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
            IsEnabledCore, (actual, expected1) => (actual == expected1),
            null, timeoutMs);
    }

    public bool IsExists()
    {
        return IsExistsCore(TryFindElement()) == true;
    }

    public bool WaitExists(bool? expected, int? timeoutMs = null)
    {
        if (expected == null) return true;
        return RunWaitWithElement(
            element => IsExistsCore(element) == expected.Value,
            timeoutMs);
    }

    public TScope AssertExists(bool? expected, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
            IsExistsCore, (actual, expected1) => (actual == expected1),
            null, timeoutMs);
    }
}
