// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls;


/// <summary>
/// Mixed control with an action Core method and an Is*Core state query.
/// </summary>

public abstract partial class MixedControl<TScope> : Base<TScope>
    where TScope : IScope<TScope>
{
    #region Click

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Visible (IsVisible / WaitVisible / AssertVisible)

    public bool? IsVisible()
    {
        return IsVisibleCore(TryFindElement()) == true;
    }

    public bool WaitVisible(bool? expected = true, int? timeoutMs = null)
    {
        return RunWaitWithElement(expected,
           element => IsVisibleCore(element) == expected!.Value,
           timeoutMs);
    }

    public TScope AssertVisible(bool? expected = true, string? message = null, int? timeoutMs = null)
    {
        return RunAssertWithElement(expected,
           IsVisibleCore, (actual, expected1) => (actual == expected1),
           message ?? $"Expected Visible to be '{expected}'. Locator: {Locator}", timeoutMs);
    }

    #endregion

}
