// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls;


/// <summary>
/// Class with multiple Core methods.
/// </summary>

public abstract partial class MultiClickable<TScope> : Base<TScope>
    where TScope : IScope<TScope>
{
    #region Click

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion
    #region Hover

    public TScope Hover()
    {
        return RunDoWithElement(element => { HoverCore(element); });
    }

    #endregion

}
