// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

namespace Brinell.Maui.Controls;

/// <summary>
/// Class with multiple Core methods.
/// </summary>
public abstract partial class MultiClickable<TScope> : Base<TScope>
    where TScope : IScope<TScope>
{

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { EnsureClickableCore(element); ClickCore(element, timeoutMs); }, timeoutMs);
    }

    public TScope Hover()
    {
        return RunDoWithElement(element => { EnsureClickableCore(element); HoverCore(element); });
    }
}
