// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

namespace Brinell.Maui.Controls;

/// <summary>
/// Simple clickable class with one Core method.
/// </summary>
public abstract partial class SimpleClickable<TScope> : Base<TScope>
    where TScope : IScope<TScope>
{

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { EnsureClickableCore(element); ClickCore(element, timeoutMs); }, timeoutMs);
    }
}
