// <auto-generated />
// This file was generated by Brinell.Generator and should not be edited manually.

#nullable enable

namespace Brinell.Maui.Controls;


/// <summary>
/// Simple clickable class with one Core method.
/// </summary>

public abstract partial class SimpleClickable<TScope> : Base<TScope>
    where TScope : IScope<TScope>
{
    #region Click

    public TScope Click(int? timeoutMs = null)
    {
        return RunDoWithElement(element => { ClickCore(element, timeoutMs); }, timeoutMs);
    }

    #endregion

}
