global using Brinell.Core.Composition;
global using Brinell.Blazor.Context;
global using Brinell.Blazor.Uat.Tests.Runtime;
global using Brinell.Blazor.UITests.PageObjects;
global using Brinell.Html.Context;
global using Brinell.Html.Interfaces;
global using Brinell.Uat;
global using Microsoft.Extensions.DependencyInjection;
global using Xunit;
