<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Brinell.Maui.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\srcnew\Brinell.Core\Brinell.Core.csproj" />
    <ProjectReference Include="..\..\srcnew\Brinell.Maui\Brinell.Maui.csproj" />
  </ItemGroup>

</Project>
